### PR TITLE
dkms-7601: Changed upstream source to https://github.com/porjo/mt7601

### PR DESCRIPTION
**Pull request by ddaygold**
I had been making fixes to my own copy of the source, but this new
upstream does it better.

I've started with the AUR mt7601-git PKGBUILD, and added dkms.

I also fixed dkms to actually work.

### CODE REVIEW

**Comment by WarheadsSE** [comment]
It does look like this will likely be pulling into mainline at that moment. My only concern is making this a severe note that there is no compatibility with before 3.19

**Comment by ddaygold** [comment]
Sorry, I'm having a hard time parsing your comment.

Do you mean this PR will be merged, or that there's a mainline alternative?

And yes, this package broke in 3.19 kernels b/c of a naming change to a struct. Should I change 
```
depends=('linux>=3.0')
```
to 
```
depends=('linux>3.19')
```

I apologize for my lack of knowledge, this is my second pull request!

**Comment by WarheadsSE** [comment]
Yup. Please update that exact part :)

**Comment by ddaygold** [comment]
Done.

I don't know if you get notifications about commits, but you clearly do about messages. Hopefully I haven't double spammed you!

**Comment by kmihelich** [comment]
Squash your commits.

**Comment by ddaygold** [comment]
Done.

I didn't realize that you could squash commits once you published them to GitHub. I thought the hard and fast rule was 'don't change shared history'. Would'a done it sooner.

**Comment by kmihelich** [comment]
Have you made sure this builds?

**Comment by ddaygold** [comment]
Tested builds on x86_64 and a beagle bone black. It works on both.

As a bonus, while testing I also fixed the .install file to correctly remove the module! 

Should've caught that the first time.

**Comment by kmihelich** [comment]
There is at least one error that will cause the build to fail.  I suggest you build using a clean chroot.

**Comment by ddaygold** [comment]
I checked again, but I don't see the problem. To be clear, it *does* build, install and function right now. Tested on x86_64 and a BBB.

What am I doing wrong?

**Comment by kmihelich** [comment]
Not building with a clean chroot. This package *will not* build in our build system as it is now.

**Comment by ddaygold** [comment]
I read the manual. 
multilib-build works now. Am I missing other problems?

**Pull request merged**
