### PR TITLE
add u-boot support for tbs2910

### PR DESCRIPTION
**Pull request by l3iggs**
Here is u-boot for the TBS2910: http://www.tbsdtv.com/products/tbs2910-matrix-arm-mini-pc.html

### CODE REVIEW

**Comment by kmihelich** [comment]
I'm not the maintainer of this package.

**Comment by l3iggs** [comment]
Fixed.

**Comment by WarheadsSE** [comment]
My concern here is doing the update to the uboot as part of the package installation vs a post-run script available in /boot

**Comment by WarheadsSE** [comment]
prod @l3iggs

**Comment by l3iggs** [comment]
@WarheadsSE, back when I wrote this and made the PR, I thought I followed the uboot packaging convention you guys were using. It looks like the PR is out of date now and unfortunately I don't have the time these days to update it to the u-boot packaging convention alarm is using today and test it properly.

Feel free to reject the PR.

**Comment by jerome-benoit** [comment]
Why this PR is not yet merged ? 
It's a proper uboot integration that should go in.

**Pull request closed without merging**
