### PR TITLE
Update kodi-rbp-git to beta 1 from alpha1

### PR DESCRIPTION
**Pull request by evils**
This updates the pkgbuild for the kodi-rbp-git package from the alpha build to the latest beta build.

### CODE REVIEW

**Comment by kmihelich** [comment]
Have you tested build and execution?

**Comment by moonman** [comment]
Have you tested it? libcec didn't compile because they updated to version 3
and we have 2.2 in repos

**Comment by evils** [comment]
I didn't expect the answer to be that fast!

It compiled successfully (in almost 12hrs ...) and it's running on my RPI2. The packages are here:
[kodi-rbp-git](https://drive.google.com/file/d/0B9fdkuHVpW82M042ZndzWi1fbUk/view?usp=sharing)
[kodi-rbp-git-eventclients](https://drive.google.com/file/d/0B9fdkuHVpW82RmFqd0VvMFJfMEk/view?usp=sharing)

The eventclients package is small and I haven't tested it (What's the eventclients version actually for?!). 
Please don't bother about the version numbers, as you can see in the package build, I haven't changed that and found that issue when it was already way too late! 
If someone might could fix that and put the right version number beta 1 has into the pkgbuild, I'm willing to compile this package again in another 12hrs :+1:

If I'm mistake by all this, I'm sorry! I only wanted to help and as beta 1 is running now for me, I believe I might be not mistaken.

**Comment by moonman** [comment]
Check cec. It compiles without it, it just won't work. We don't put beta1
etc in package versions.

**Comment by evils** [comment]
```
------------------------
  Kodi Configuration:
------------------------
  Kodi Version:	15.0-BETA1
  git Rev.:	Unknown
  Debugging:	No
  Profiling:	No
  Optimization:	Yes
  SWIG Available:	Yes
  JRE Available:	Yes
  Doxygen Available:	No
  Crosscomp.:	No
  target ARCH:	arm
  target CPU:	arm1176jzf-s
  OpenGLES:	Yes
  ALSA:		Yes
  DBUS:		Yes
  VDPAU:	No
  VAAPI:	No
  VTBDecoder:	No
  OpenMax:	No
  Joystick:	No
  XRandR:	No
  Waveform:	Yes
  Spectrum:	Yes
  GOOM:		No
  RSXS:		Yes
  FishBMC:	No
  ProjectM:	No
  Touch skin:	No
  X11:		No
  Wayland:	No
  Bluray:	Yes
  TexturePacker:No
  MID Support:	No
  ccache:	No
  ALSA Support:	Yes
  PulseAudio:	No
  DVDCSS:	Yes
  Google Test Framework Configured:	Yes
  Google Breakpad Configured:	No
  Avahi:	Yes
  mDNSEmbedded:	No
  Non-free:	Yes
  ASAP Codec:	No
  MySQL:	Yes
  Webserver:	Yes
  libssh support:	Yes
  libRTMP support:	Yes
  libsmbclient support:	Yes
  libnfs client support:Yes
  AirPlay support:	Yes
  AirTunes support (libshairplay):	Yes
  UPnP support:		Yes
  Optical drive:	Yes
  libudev support:	Yes
  libusb support:	No
  libcec support:	Yes
  libcap support:	Yes
  additional players:	Yes, omxplayer
  additional codecs:	No
  prefix:	/usr
------------------------

```

Libcec seems to be in, can't say which version. Close it if you think it's a faulty build.

**Comment by moonman** [comment]
I won't  close it, i'll double check tonight. It wouldn't find libcec for
me 3 days ago that's why I'm wondering.

**Comment by moonman** [comment]
I see what happened: You pointed directly to beta1 commit, which is before libcec3 change. I usually use the latest commit at the date I build.
For reference, this is the change to libcec3: https://github.com/xbmc/xbmc/commit/be8f33d1468a295612b914eca8b59aa87cb67e8d

Anyway, committed your changes along with a couple more: https://github.com/archlinuxarm/PKGBUILDs/commit/b712a837510601e0c5a98050085715baba79c8e9
Thanks.

**Pull request closed without merging**
