### PR TITLE
kodi-imx to 14.1

### PR DESCRIPTION
**Pull request by beam**

### CODE REVIEW

**Comment by pepedog** [comment]
You built this ok?

**Comment by beam** [comment]
didn't try

**Comment by WarheadsSE** [comment]
Then this won't be merged.

**Comment by pepedog** [comment]
Why didn't you try to build? Only takes 2 hours on a 4 core.

**Comment by beam** [comment]
I'm not sure how to do that. I don't want compile on cubox, and cross-platform is a little bit complicated for me.

**Comment by pepedog** [comment]
I don't know why you find building hard (especially on the cubox itself), I just tried and it built fine so I just committed again https://github.com/archlinuxarm/PKGBUILDs/commit/2a2479a65bd9cabc930056e47d607a2130cb5b49

**Comment by beam** [comment]
i tried build on cubox but it crash during ffmpeg compile, you have ffmpeg installed from packages?

**Pull request closed without merging**
