### PR TITLE
core/linux-odroid-xu3 to 6.6.68

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by graysky2** [comment]
Looks like some significant changes to the config with this PR... have you confirmed?

**Comment by polyzen** [comment]
`+CONFIG_ARM64=y` 🤔no idea why that happened.

Added the `config` changes from my build that I had forgotten to include.

**Comment by graysky2** [comment]
I'm still getting tons of config changes... when you built this did you not?

**Comment by graysky2** [comment]
My bad... typo in script was cross compiling with aarch64 not armv7h

**Pull request closed without merging**
