### PR TITLE
Include patch from upstream to fix font rendering on some ARM boards

### PR DESCRIPTION
**Pull request by bhush9**
See: https://codereview.qt-project.org/#/c/185259/

This patch likely won't be included in the archlinux main repo currently
so submitting this here

### CODE REVIEW

**Comment by kmihelich** [comment]
What have you tested this on where you see an improvement?

**Comment by bhush9** [comment]
I've tested this patch on Nexus 5X earlier along with libhybris, and Plasma mobile.. Without this patch font rendering in qtquick Text items was broken, while this patch fixes it

**Comment by kmihelich** [comment]
So nothing supported by this project.  It appears to have been merged, so it'll be there in the next version.

**Comment by bhush9** [comment]
It unfortunately won't be available soon, given qt is not planning to release 5.8.x point releases, lists.qt-project.org/pipermail/releasing/2017-February/004471.html and relevant bugfixes should be manually backported b packagers.

**Comment by bhush9** [comment]
Ping?

**Pull request closed without merging**
