### PR TITLE
alarm: create dkms-mali-utgard-meson

### PR DESCRIPTION
**Pull request by jakogut**
DKMS package for Mali Utgard kernel driver on meson platform

### CODE REVIEW

**Comment by kmihelich** [comment]
Missing buildarch, and the note about kernel version in the package description is probably overkill.

**Comment by jakogut** [comment]
Thanks for the feedback, updated.

**Comment by kmihelich** [comment]
I thought this needed at least 4.12?  You have greater than in the depends.

**Comment by jakogut** [comment]
Good catch, fixed. I also changed the pkgver to match the userspace mali libGL packages.

**Pull request merged**
