### PR TITLE
extra/mesa: enable Freedreno driver

### PR DESCRIPTION
**Pull request by akaWolf**

### CODE REVIEW

**Comment by theironrobin** [comment]
did you test that it builds? mesa can be finicky.

**Comment by akaWolf** [comment]
> did you test that it builds? mesa can be finicky.

yeah, I've tested.

**Comment by akaWolf** [comment]
@davidbeauchamp does it looks good for you?

**Comment by akaWolf** [comment]
@davidbeauchamp bump

**Comment by rocketstrong600** [comment]
works on my oneplus 6 with the kernel from postmaketos

**Comment by 1ace** [comment]
just fyi, #1973 is identical, so whichever lands the other one can be closed :)

**Comment by akaWolf** [comment]
resolved conflict

**Comment by akaWolf** [comment]
@davidbeauchamp ping

**Review by 1ace — APPROVED** [review]

**Comment by theironrobin** [comment]
any updates on this after 1 month with approval and no merge?

**Comment by syboxez** [comment]
Was about to make another PR for this until I saw this. Any update on getting this merged?

**Pull request closed without merging**
