### PR TITLE
core/linux-odroid-c1: Include btrfs in C1 kernel

### PR DESCRIPTION
**Pull request by djmaze**
This changes the kernel for the ODROID-C1 to include btrfs in the kernel as opposed to a module. This allows using brtfs as a root filesystem. (`/boot` must reside on a separate ext*/fat/whatever partition, as AFAIK Uboot does not support booting from btrfs yet.)

I am using this to benefit from btrfs advantages compared to ext4: Easier "partition" management, backups and rollbacks through subvolumes, multi-device support. Also, a better experience with Docker (see https://github.com/archlinuxarm/PKGBUILDs/issues/963#issuecomment-72756639). So you just need one small ext4 partition for the static boot files and one big btrfs partition for everything else.

### CODE REVIEW

**Comment by kmihelich** [comment]
Was the config edited by hand?

**Comment by djmaze** [comment]
Yes.. I was not sure which was the best way on how to do this. I should better do it again with `make menuconfig` in order to get the additional options in the config, I suppose?

**Comment by kmihelich** [comment]
Yes, you should.  Hence why the very top of the config says: Automatically generated file; DO NOT EDIT.

**Comment by djmaze** [comment]
Ok, sorry. Will update this.

**Comment by djmaze** [comment]
Ok, updated. I also enabled btrfs debugging support, as it is enabled for ext4 as well.

Also confirmed it is working.

**Comment by kmihelich** [comment]
Is debugging required?

**Comment by djmaze** [comment]
From my experiences, there are no problems with btrfs in the latest kernels anymore. So we might as well disable debugging.

**Comment by djmaze** [comment]
Disabled debugging support now.

**Pull request merged**
