### PR TITLE
Add xfs support to the linux-odroid-c1 kernel package.

### PR DESCRIPTION
**Pull request by cjordan**
The options in this commit are the same as the standard arch kernel.

### CODE REVIEW

**Comment by kmihelich** [comment]
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md#arch-linux-arm-specific-packages

**Comment by kmihelich** [comment]
Was the config edited by hand?

**Comment by cjordan** [comment]
No, I used the nconfig option from the PKGBUILD and copied it over.  I've
compiled it and am running it successfully.

On 6 March 2015 at 15:36, Kevin Mihelich <notifications@github.com> wrote:

> Was the config edited by hand?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archlinuxarm/PKGBUILDs/pull/1124#issuecomment-77505486>
> .
>



-- 
Christopher Jordan
PhD Candidate - Astrophysics
University of Tasmania

Bachelor of Engineering (Honours) - Bachelor of Science (Electrical &
Electronic Engineering, Mathematics)
Email:  christopher.jordan@utas.edu.au <christopher.jordan@jcu.edu.au>

**Comment by kmihelich** [comment]
Whatever you did, it's not the output from nconfig. That is unacceptable.

Additionally, enabling xfs disables user_ns, which is used by containers.  This kernel needs a patch set applied before xfs will be enabled.

**Pull request closed without merging**
