### PR TITLE
libbcm2835 1.42, RPi2 support

### PR DESCRIPTION
**Pull request by larsch**

### CODE REVIEW

**Comment by kmihelich** [comment]
This will not build for v7 in our build system.  Read the README again.

Where did that patch come from, and why is it needed?

**Comment by larsch** [comment]
buildarch updated.

I created the patch. The inline assembly in the upstream is not accepted by current gcc assembler due to missing newlines.

**Comment by kmihelich** [comment]
You need to clean up the patch and get rid of the extraneous text.

**Comment by larsch** [comment]
Fair. Done.

**Pull request merged**
