### PR TITLE
Updated linux-utilite to 4.1.15 1.2.0-ga

### PR DESCRIPTION
**Pull request by nenadperic**
CompuLab released new kernel version (4.1.15) for the Utilite. Since I have a few of them running Arch, I figured I could try and update the package.

The config is based on the CompuLab config with a few modifications I picked up from linux-armv7. I've tested this on a Utillite Pro (with 32GB SSD). I have the latest CompuLab u-boot running on them (U-Boot 2015.07-cm-fx6-3).

Please let me know if you find anything missing.

**Changes:**
- Updated to version 4.1.15_1.2.0_ga - http://git.freescale.com/git/cgit.cgi/imx/linux-2.6-imx.git

### CODE REVIEW

**Comment by rkorn86** [comment]
I have hdmi output from console, but kodi exits with egl error 3003. Seems like mxc gpu accecleration does not work. You have the same result?

**Comment by nenadperic** [comment]
TBH, I never got to plugging anything into the HDMI port (I'm just using it as an MPD server), so I don't really know if MXC acceleration is working or not. I want to try Kodi, but didn't get around to it yet.

**Comment by pepedog** [comment]
You have to check kernel source, in the file drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal_version.h, version matches package imx-gst-viv version

**Comment by rkorn86** [comment]
I guess you mean imx-gpu-viv-*. Yeah, I updated my imx-gpu-viv-fb manually to 5.0.11.p8.4-1 by updating PKGBUILD locally. Without success.

**Comment by rkorn86** [comment]
Changing drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal_version.h to match /opt/fsl/include/HAL/gc_hal_version.h from imx-gpu-viv-fb version 5.0.11.p4.5-1 did not help either.

**Comment by rkorn86** [comment]
I've built galcore.ko as module using CONFIG_MXC_GPU_VIV_3_14_28=y on a wandboard Quad 4.1.15 Kernel https://github.com/wandboard-org/linux and dont get any kernel and user space version missmatch anymore (EGL Error 3003). Instead i get the following error:
```20:08:32.588 T:1912299536   ERROR: EGL error in BindContext: 300b
20:08:32.588 T:1912299536   ERROR: CreateWindow: Could not bind to context
20:08:32.588 T:1912299536   ERROR: CreateNewWindow: Could not create new window
20:08:32.588 T:1912299536   FATAL: CApplication::Create: Unable to create window```

**Comment by rkorn86** [comment]
Corrected my DTS and it seems to work now. Nevermind....

**Comment by pepedog** [comment]
The forum is the best place to discuss what works.

**Comment by nenadperic** [comment]
I'm having issues with this kernel, specifically, the EXT4 file system on MSATA seems to get corrupt from time to time, so I'm closing this pull request.

**Pull request closed without merging**
