### PR TITLE
core/linux-aarch64-rc: Enable OV5640 camera driver

### PR DESCRIPTION
**Pull request by barni2000**
OV5640 driver is added as a module to the config.

### CODE REVIEW

**Comment by barni2000** [comment]
I hope in the next kernel release the camera drivers will be enabled. I close this because this PR is deprecated. I will wait for 5.11

**Comment by graysky2** [comment]
https://archlinuxarm.org/forum/viewtopic.php?f=3&t=15031

**Comment by barni2000** [comment]
@graysky2 Your link is related to rpi4. This is the general kernel.

**Comment by graysky2** [comment]
@barni2000 - Missed that, agreed.

**Pull request closed without merging**
