### PR TITLE
core/linux-wandboard replaced kernel from @wandboard-org with 3.14 running on the Cubox-I

### PR DESCRIPTION
**Pull request by CrawX**
This replaces the wandboard kernel from the official @wandboard-org github account with a forked version of the kernel developed by @linux4kix published at [CrawX/linux-linaro-stable-mx6](https://github.com/CrawX/linux-linaro-stable-mx6). I added the dts and the rfkill driver from the @wandboard-org kernel.
See [this thread](http://forums.wandboard.org/viewtopic.php?f=12&t=666) in the wandboard forums.

This kernel runs fine on my wandboard quad rev b. In fact, it is more stable than the official kernels have ever been. Huge thanks to @linux4kix! I've been running this particular kernel for a few weeks now.
I have not tested this on other versions (single, dual) as well as revisions.

As my use case is mostly kodi (gpu, vpu, hdmi, no x11, sata, ethernet) I have not tested every single wandboard feature. I can say that the aforementioned as well as Wifi work. I have not tested other features like bluetooth, or gpios.

I'd be happy to receive some feedback on this.

Happy holidays!

### CODE REVIEW

**Comment by crazzell** [comment]
I have this version running on a Wandboard dual-lite rev b. (uname -r shows 3.14.14-1).  Only issue I'm facing is that WiFi doesn't survive through a reboot process. I have to restart by interrupting the dc power to the board to get WiFi back up. Is this a known issue?

**Comment by jokogr** [comment]
Hello,

I have a Wandboard Quad rev. A and I have applied a hardware fix to properly route the CEC signal (for more details please check [here](https://www.project-insanity.org/blog/2014/01/24/wandboard-with-hdmi-cec-and-xbmc/)).

The thing is that the last kernel where CEC is working properly in my setup is 3.10.17-4. Everything above (3.10.17-5 or 3.14.x-x) seems not to be working. Could anyone help me?

Thanks in advance

**Comment by CrawX** [comment]
This is pretty much outdated now.

In the meantime, another very good kernel fork made by SolidRun has surfaced. It's based on linux-fslc and can be found in [SolidRun's GitHub](https://github.com/SolidRun/linux-fslc). I've added some modifications to allow it to run on the Wandboard (SolidRun/linux-fslc#29) and @linux4kix has expressed that he's very open to merging this after review.

I've had a very good experience with this fork (PKGBUILDs can be found [here](https://github.com/CrawX/PKGBUILDs/tree/experimental)) and I expect it to be the same on other imx6 devices, at least on SolidRun's Cubox-I. There are also other pull requests (SolidRun/linux-fslc#27) for other imx6 device trees.

I have only tested this on the revision B of the Wandboard Quad so far but in my opinion this kernel should be considered to be the standard kernel for all (compatible) imx6 devices, especially seeing that core/linux-wandboard has been recently removed.

If this is the wrong place for this discussion, I could create a post on the forums.

**Comment by kmihelich** [comment]
If there is well-maintained (with some form of promise to maintain) source that can provide one i.mx6 kernel to encompass all supported devices, I don't mind having it here.  Especially if someone else maintains it.

Having tried multiple trees with varying degrees of quality and lack of maintenance, mainline is the simpler way forward and there is fairly good support there (including GPU, crypto, etc.).  In this PR I'm counting five kernel trees mentioned to support a device, and that's just silly.

**Pull request closed without merging**
