### PR TITLE
Add mali-bifrost-g31-libgl-x11-gbm

### PR DESCRIPTION
**Pull request by valadaa48**
Turns out the -gbm lib wasn't enough so I'm adding the x11-gbm lib as well. I re-introduced the pkgbase mechanism. I left the revision at 1 since for the original package the only thing that changed was the description (adds "(gbm)"). If you prefer that I bump the revision then I can certainly fix this.

Tested locally on my OGA and it works as expected.

Thanks!

### CODE REVIEW

**Comment by kmihelich** [comment]
Due to build system particulars, instead of renaming please make one commit that removes the old package and then a separate commit that adds the new split package.

**Comment by valadaa48** [comment]
Sure thing, will do in a min

**Comment by valadaa48** [comment]
Will the build system re-build the -gbm library even though it's the same version+rel? Would be nice to ensure the pkgdesc is updated in the package.

**Comment by kmihelich** [comment]
Yes, it will be rebuilt in the new split package.

**Comment by valadaa48** [comment]
Perfect, thanks. Committed in 2 separate commits.

**Pull request merged**
