### PR TITLE
[uboot-sunxi] add a20-olinuxino-lime2

### PR DESCRIPTION
**Pull request by ventosus**
Add u-boot-sunxi target for A20-OLinuXino-Lime2 board.

### CODE REVIEW

**Comment by kmihelich** [comment]
pkgrel needs to be bumped.  And have you checked that it builds?

**Comment by ventosus** [comment]
>> pkgrel needs to be bumped
bumped (shame on me)

>> And have you checked that it builds?
- yes, I've checked on my A20-OLinuXino-Lime2
- builds fine (both on pod directly & cross-compiled on x86_64)
- installs fine
- boots linux-armv7 and linux-sun7i fine

**Comment by ventosus** [comment]
I have a related pull-request running for sunxi-boards to merge OLIMEX's recently updated .fex files.

https://github.com/linux-sunxi/sunxi-boards/pull/40

**Comment by kmihelich** [comment]
Do you want to wait until that is merged?

**Comment by ventosus** [comment]
Yes, I think this would be sensible.
I'll report back here once the .fex files have been updated ...

**Comment by kmihelich** [comment]
Since your fex PR also includes the first Lime, would you mind tacking a package for that into this PR?

**Comment by kmihelich** [comment]
Is not having the updated fex files a show-stopper?

**Comment by ventosus** [comment]
Not a show stopper at all.
I boot to 'linux-armv7' on my Lime2 in the first place, which uses device trees...

The boards will boot just fine with 'linux-sun7i' and the outdated fex files.

People anyway need to adapt the fex definitions manually depending on what
peripherals they use (VGA, HDMI, ...)

PR thus can be applied.

**Pull request merged**
