### PR TITLE
gcc: switch gcc to the latest snapshot on the gcc-6-branch

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

### CODE REVIEW

**Comment by kmihelich** [comment]
No.

**Comment by jerome-benoit** [comment]
May I have an real explanation of the reject ?

Your project do not have a central place where people can discuss about changes before submit them (no mailling list, no bugs tracker, no responses on IRC, etc.). 

And when people are willing to improve stuff, they do not even have an explanation when their work is not accepted. 

Your project ship broken image for almost all ARMv7 SoC because of latest update to systemd surely untested, a buggy version of GCC, an unstable version of ODROID XU kernel - wifi driver is deadlocking -, the transition to mainline kernel is also untested (just try it on cubox or ODROID XU, u-boot version do not support compressed kernel image), and so on ...

So if you think it's a fine way to manage a project and newcomers, you're wrong and I will probably stop pushing fixes upstream and open a pacman repository where people will to able to grab fixed uboot, fixed gcc, fixed odroid-xu kernel, and so ...

**Comment by kmihelich** [comment]
May I have a real explanation as to why this needed to be merged?

You're dumping changes on critical, core components to this project with *zero* explanation as to why they're needed, in *direct violation* of the stated rules for contribution.  When you get around to actually reading them, perhaps you'll understand why your pull requests keep getting rejected.  You've also failed to provide any details on how you have validated this new version of the toolchain on all four supported architectures, and how this version will behave against the other 5000 packages that need to be built with it.  Upgrading the toolchain is not a light matter, and also involves a significant amount of my time testing the corresponding cross-compiler toolchains that need to be built to match the native versions.  You have given *zero* insight into any of these matters.  Furthermore, this exceeds the version used by upstream Arch Linux (yet another rule you have disregarded), where the current toolchain versions have gained additional testing.  If the new version of this toolchains breaks any of the packages that use older source code built against older standards, this is now our problem to attempt to solve, adding even further work on an already stretched thin (completely free-time) budget.  None of this work you have made any mention of, or offer towards testing compatibility and addressing the problems on your own time in a timely matter.  It also demonstrates your complete lack of understanding and disregard as to how a distribution such as this one needs to operate.

You are free to discuss potential changes on both the forum and IRC.  You might not get an immediate response.  Go through the git log here and count how many active developers there are for this project, and this should clear up why this is the case.  Also note that like nearly all open source projects, there are precisely zero people employed to work on this full time.  This project continues to operate at the significant expense of both my free time *and* money; a project provided at zero cost to you.

When people are willing to improve stuff, they should clearly state what their changes are doing so that they don't have to be guessed at or reversed engineered.  If you can't provide an explanation for your submission, why do you feel entitled to receive an explanation for the rejection?  Contributing to any open source project will have the same guidelines.

The 56 systems across four architectures currently running within my line of sight with the latest packages are a testament to the non-brokenness of this distribution.  Your perceptions of bugginess are entirely your own, and unaddressable with your complete and utter lack of any kind of supporting information.  Additionally, your only noted complaints here address systems that have been EOL'd or completely abandoned and disowned by their manufacturers, and correspondingly receive less attention here compared to systems with active support and upstream contributions.  And again, count the number of active developers here.  Spouting your misinformed observations bereft of any consideration for work going on behind the scenes does not help anything, and the attacks only serve to embitter any consideration of future contributions made by yourself.

So yes, I do think this is a fine way for a single person to manage a project of this size and scope, given the time constraints. If you can't be bothered to follow the rules for contribution for this project, expect any and all future contributions to be treated in the same respect you're showing this project.  Your attitude and blatant disregard for the established procedures will not be tolerated here, nor by any other project.

This will be the last explanation given to you.  You can choose to adhere to the posted procedures and submit useful contributions, or stop being surprised that your submissions are summarily rejected.

**Comment by jerome-benoit** [comment]
Fair enough for this PR that lack explanation and testing on critical component . 

But on this PR https://github.com/archlinuxarm/PKGBUILDs/pull/1394, I still think you should have merged it because it fix the issue and the mainline kernel migration is not yet functional on this hardware. Take it has an interim fix before I have time to work on the mainline kernel migration for this hardware, and review it for things that need to be changed for you to merge it.  

I test every single change I made on real hardware. I think having better support for old hardware is orthogonal to adding support to new hardware. Being old do not mean not useful anymore to people having them :)

**Pull request closed without merging**
