### PR TITLE
core/linux-aarch64 to 5.10.7-1

### PR DESCRIPTION
**Pull request by xdarklight**
The result boots fine for me on 64-bit Amlogic meson boards

drop ``0005-arm64-module-set-trampoline-section-flags-regardless.patch`` because is already included upstream

### CODE REVIEW

**Comment by Alarmrpi** [comment]
Can confirm multiple raspberry-pi 4 (4gb) boots and works fine.

**Comment by a-andre** [comment]
Kernel 5.9 reached EOL. Maybe you want to raise the version to 5.10.x

**Comment by xdarklight** [comment]
I just updated this to 5.10.7

I don't expect the maintainers to do anything about this though.
this PR is pending for two months now and the kernel shipped by Arch Linux ARM is outdated has unpatches vulnerabilities.
so I personally consider the linux-aarch64 and linux-armv7 (and possibly some others) as unmaintained, with all the problems this comes with.

**Comment by sknsean** [comment]
I really wish archlinux.org would start aarch64 support.
The spirit of ArchLinux is lost in alarm :(

**Comment by graysky2** [comment]
> I really wish archlinux.org would start aarch64 support.
The spirit of ArchLinux is lost in alarm :(

If you are using a Raspberry Pi 4:
* The [rpi-5.4.y](https://github.com/raspberrypi/linux/commits/) kernel for aarch64 right now; it is provided in the official repos.
* The developing (pretty mature right now) [rpi-5.10.y](https://github.com/raspberrypi/linux/commits/rpi-5.10.y) kernel is provided in my unofficial repo, or you can build it yourself.  See [this](https://archlinuxarm.org/forum/viewtopic.php?f=3&t=15031) announcement.

**Comment by sknsean** [comment]
> If you are using a Raspberry Pi 4:
> 
>     * The [rpi-5.4.y](https://github.com/raspberrypi/linux/commits/) kernel for aarch64 right now; it is provided in the official repos.
> 
>     * The developing (pretty mature right now) [rpi-5.10.y](https://github.com/raspberrypi/linux/commits/rpi-5.10.y) kernel is provided in my unofficial repo, or you can build it yourself.  See [this](https://archlinuxarm.org/forum/viewtopic.php?f=3&t=15031) announcement.

I'm using a vanilla/mainline kernel for my espressobin + rpi4's not interested in other forks.
It would be far easier to just run `pacman -Syu` to update them :)

**Comment by xdarklight** [comment]
> If you are using a Raspberry Pi 4:

I only have boards with various Amlogic SoCs, which is why I am interested in linux-aarch64

**Comment by xdarklight** [comment]
Thank you @kmihelich !

**Pull request closed without merging**
