### PR TITLE
add community/blender

### PR DESCRIPTION
**Pull request by zervanko**
**Description:** add blender package from Arch Linux to ALARM

**Changes:**
- disable CUDA to add ability for build blender on ARM devices.
- add buildarch=12 to build ot only for armv7h and aarch64 (but I didn't changed "arch" var, because I don't know, should I do it or no.)

**Reason to merge:** Ghm.. actually, I don't know. My mate @initrider have taken me out with a request to make "true" PKGBUILD. I don't know such about this distro, but I tried to follow rules and examples, which are available here. So the reason is: add blender package to community repo.

### CODE REVIEW

**Comment by initrider** [comment]
Oh, common, he do it every time!

**Comment by zervanko** [comment]
@initrider don't be silly! As I said before, read that https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md Maybe there is something, that I've missed, because "Pull requests that fail to meet these requirements may be summarily closed without response.". Maybe he is too attentive to details. I will try to find my mistakes.

**Comment by initrider** [comment]
@zervanko yea yea, don't try. He will never do it due to his strange reasons, which he will never tell me. I think, he just don't love blender. I've contacted to maintainer to remove gcc6, but as I see, it doesn't metter. 😣

**Comment by zervanko** [comment]
@initrider calm down, there is no reason to feel angry about such stuff. Have you tried to ask him that way?
@kmihelich can you please specify my mistakes, because I really don't know, what am I doing wrong? Or have you got some other reasons?

**Comment by initrider** [comment]
@zervanko ha-ha, loser. He will not answer you, because he is not a human, but something really strange. I've tried IRC and forum's messages, but it doesn't work. And he doesn't have Telegram or something else (I've checked it on Google).

**Pull request closed without merging**
