### PR TITLE
add pcduino3-nano to uboot-sunxi/PKGBUILD

### PR DESCRIPTION
**Pull request by Thermionix**
added pcduino3-nano pkg

### CODE REVIEW

**Comment by WarheadsSE** [comment]
Pkgver
Pkgrel

You've of course built this yourself?

**Comment by Thermionix** [comment]
Yep have built - required to get the ethernet working on my Nano
Not sure where to send a pull request to get `sun7i-a20-pcduino3-nano.dtb` included in `/boot/dtbs` in the armv7 image

**Comment by kmihelich** [comment]
Squash the commits.

**Comment by Thermionix** [comment]
Squashed

**Comment by Thermionix** [comment]
ah, I see `sun7i-a20-pcduino3-nano.dts` went [into kernel 4.2](http://lists.infradead.org/pipermail/linux-arm-kernel/2015-May/342400.html)

**Comment by kmihelich** [comment]
You have obviously not built this yourself in a clean chroot.  This is unacceptable.
https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot

**Pull request closed without merging**
