### PR TITLE
core/linux-aarch64: Enable DRM_VMWGFX as a module

### PR DESCRIPTION
**Pull request by k-ronny**
This driver is available for the X86 and ARM64 architectures and allows Arch Linux ARM to be used with VMware Fusion (currently Public Tech Preview 22H2).

### CODE REVIEW

**Comment by The-King-of-Toasters** [comment]
Are you using this with the svga mesa driver for 3d acceleration?

**Comment by k-ronny** [comment]
Yes, I use it with mesa 22.2.0-rc3 and it runs great.
```
=======================================================
    glmark2 2021.12
=======================================================
    OpenGL Information
    GL_VENDOR:      VMware, Inc.
    GL_RENDERER:    SVGA3D; build: RELEASE;  LLVM;
    GL_VERSION:     4.3 (Compatibility Profile) Mesa 22.2.0-rc3
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0
    Surface Size:   1920x1200 fullscreen
=======================================================
[build] use-vbo=false: FPS: 2661 FrameTime: 0.376 ms
[build] use-vbo=true: FPS: 3278 FrameTime: 0.305 ms
[texture] texture-filter=nearest: FPS: 3223 FrameTime: 0.310 ms
[texture] texture-filter=linear: FPS: 3237 FrameTime: 0.309 ms
[texture] texture-filter=mipmap: FPS: 3205 FrameTime: 0.312 ms
[shading] shading=gouraud: FPS: 3219 FrameTime: 0.311 ms
[shading] shading=blinn-phong-inf: FPS: 3123 FrameTime: 0.320 ms
[shading] shading=phong: FPS: 3218 FrameTime: 0.311 ms
[shading] shading=cel: FPS: 3204 FrameTime: 0.312 ms
[bump] bump-render=high-poly: FPS: 2803 FrameTime: 0.357 ms
[bump] bump-render=normals: FPS: 3334 FrameTime: 0.300 ms
[bump] bump-render=height: FPS: 3335 FrameTime: 0.300 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 3132 FrameTime: 0.319 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 1658 FrameTime: 0.603 ms
[pulsar] light=false:quads=5:texture=false: FPS: 3178 FrameTime: 0.315 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 437 FrameTime: 2.288 ms
[desktop] effect=shadow:windows=4: FPS: 710 FrameTime: 1.408 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 791 FrameTime: 1.264 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 802 FrameTime: 1.247 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 836 FrameTime: 1.196 ms
[ideas] speed=duration: FPS: 1648 FrameTime: 0.607 ms
[jellyfish] <default>: FPS: 2901 FrameTime: 0.345 ms
[terrain] <default>: FPS: 215 FrameTime: 4.651 ms
[shadow] <default>: FPS: 1480 FrameTime: 0.676 ms
[refract] <default>: FPS: 179 FrameTime: 5.587 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 3167 FrameTime: 0.316 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 3172 FrameTime: 0.315 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 3161 FrameTime: 0.316 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 3182 FrameTime: 0.314 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 3174 FrameTime: 0.315 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 3185 FrameTime: 0.314 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 3208 FrameTime: 0.312 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 3196 FrameTime: 0.313 ms
=======================================================
                                  glmark2 Score: 2462 
=======================================================
```

**Comment by The-King-of-Toasters** [comment]
hmm, I tried adding `svga` to mesa but I'm still getting llvmpipe. Can you share your PKGBUILD diffs that you made to enable this?

**Comment by k-ronny** [comment]
```
diff --git a/extra/mesa/PKGBUILD b/extra/mesa/PKGBUILD
index ffd112d3e..e004f88a0 100644
--- a/extra/mesa/PKGBUILD
+++ b/extra/mesa/PKGBUILD
@@ -14,9 +14,9 @@ highmem=1
 pkgbase=mesa
 pkgname=('vulkan-mesa-layers' 'opencl-mesa' 'vulkan-radeon' 'vulkan-swrast' 'vulkan-broadcom' 'vulkan-panfrost' 'libva-mesa-driver' 'mesa-vdpau' 'mesa')
 pkgdesc="An open-source implementation of the OpenGL specification"
-pkgver=22.1.6
+pkgver=22.2.0_rc3
 pkgrel=1
-arch=('x86_64')
+arch=('aarch64' 'x86_64')
 makedepends=('python-mako' 'libxml2' 'libx11' 'xorgproto' 'libdrm' 'libxshmfence' 'libxxf86vm'
              'libxdamage' 'libvdpau' 'libva' 'wayland' 'wayland-protocols' 'zstd' 'elfutils' 'llvm'
              'libomxil-bellagio' 'libclc' 'clang' 'libglvnd' 'libunwind' 'lm_sensors' 'libxrandr'
@@ -24,10 +24,10 @@ makedepends=('python-mako' 'libxml2' 'libx11' 'xorgproto' 'libdrm' 'libxshmfence
 url="https://www.mesa3d.org/"
 license=('custom')
 options=('debug')
-source=(https://mesa.freedesktop.org/archive/mesa-${pkgver}.tar.xz{,.sig}
+source=(https://mesa.freedesktop.org/archive/mesa-${pkgver//_/-}.tar.xz{,.sig}
         LICENSE)
-sha512sums=('3b2a0bb781c3d540401e6f51e3cf0d87d4e22923b6a5a4ea9d8ce5c79b4a2d5e8b1c237a36325d7d7178448ae102470ebefb312644dc09818cce91fd5439cb07'
-            'SKIP'
+sha512sums=('e026904fbc046575d58c5458e2d94d201cbb015eaf5e900eefbc237f45ebd0e6afb46b4d74b0c9b864911e174a1729707e9f85fea54996ba87499b33c4c96836'
+            '2e1da2185211587dd01bc8bb378e66a9c8a187611bb53a2b7df86fdae1f7b9b66379c382a765ad5a66ef5a1de3e3e89d3d1248b6ce1e79c1401388bc96e37e9d'
             'f9f0d0ccf166fe6cb684478b6f1e1ab1f2850431c06aa041738563eb1808a004e52cdec823c103c9e180f03ffc083e95974d291353f0220fe52ae6d4897fecc7')
 validpgpkeys=('8703B6700E7EE06D7A39B8D6EDAE37B02CEB490D'  # Emil Velikov <emil.l.velikov@gmail.com>
               '946D09B5E4C9845E63075FF1D961C596A7203456'  # Andres Gomez <tanty@igalia.com>
@@ -37,14 +37,14 @@ validpgpkeys=('8703B6700E7EE06D7A39B8D6EDAE37B02CEB490D'  # Emil Velikov <emil.l
               '57551DE15B968F6341C248F68D8E31AFC32428A6') # Eric Engestrom <eric@engestrom.ch>
 
 prepare() {
-  cd mesa-$pkgver
+  cd mesa-${pkgver//_/-}
 
 }
 
 build() {
   case "${CARCH}" in
     armv7h)  GALLIUM=",etnaviv,kmsro,lima,panfrost,tegra,v3d,vc4" ;;
-    aarch64) GALLIUM=",etnaviv,kmsro,lima,panfrost,v3d,vc4" ;;
+    aarch64) GALLIUM=",etnaviv,kmsro,lima,panfrost,svga,v3d,vc4" ;;
   esac
 
   # Build only minimal debug info to reduce size
@@ -57,7 +57,7 @@ build() {
     CXXFLAGS+=' -mtls-dialect=gnu'
   fi
 
-  arch-meson mesa-$pkgver build \
+  arch-meson mesa-${pkgver//_/-} build \
     -D b_lto=$([[ $CARCH == aarch64 ]] && echo true || echo false) \
     -D b_ndebug=true \
     -D platforms=x11,wayland \
```

**Comment by The-King-of-Toasters** [comment]
I hate to turn this pr into a tech support discussion, but I'm finding the driver support *very* flaky compared to e.g. Fedora Rawhide.

I couldn't get it to work on an existing VM, so I started fresh with a recompiled kernel/mesa and it worked! Then when I started migrating my setup/packages over, `vmwgfx` suddenly started failing hard. Looking at `dmesg` log, I keep getting `Failed to update STDU` errors and xorg/sway hangs. And now I can't even get that because llvmpipe is being preferred.

Could you share your list of packages so I can do some more digging on this?

**Comment by k-ronny** [comment]
To be able to use sway, I had to set this environment variable:
```
WLR_NO_HARDWARE_CURSORS=1
```

**Comment by The-King-of-Toasters** [comment]
See, I try using that and I still get a black screen. And if I use i3 instead, fusion encounters an error and has to shut down the VM.

**Comment by k-ronny** [comment]
I don't know what is missing in your environment.
I only use available packages and mesa with added svga driver.
I tried mesa version 22.1.7 and version 22.2.0-rc3. Both versions work well.
Because I start sway with gdm, I created the following desktop file:
```
/usr/share/wayland-sessions/mysway.desktop

# bof mysway.desktop

[Desktop Entry]
Name=mySway
Comment=An i3-compatible Wayland compositor
Exec=env MOZ_ENABLE_WAYLAND=1 WLR_NO_HARDWARE_CURSORS=1 sway
Type=Application

# eof
```
That's it.

```
k_ronny@archlinux ~ > uname -a
Linux archlinux 5.19.4-1-aarch64-ARCH #1 SMP PREEMPT Sat Aug 27 14:19:21 MDT 2022 aarch64 GNU/Linux
```

```
k_ronny@archlinux ~ > pacman -Qi mesa
Name                     : mesa
Version                  : 22.1.7-1
Beschreibung             : An open-source implementation of the OpenGL specification
Architektur              : aarch64
URL                      : https://www.mesa3d.org/
Lizenzen                 : custom
Gruppen                  : Nichts
Stellt bereit            : mesa-libgl  opengl-driver
Hängt ab von             : libdrm  wayland  libxxf86vm  libxdamage  libxshmfence  libelf  libomxil-bellagio  libunwind  llvm-libs  lm_sensors  libglvnd  zstd  vulkan-icd-loader
                           libsensors.so=5-64  libexpat.so=1-64  libvulkan.so=1-64
Optionale Abhängigkeiten : opengl-man-pages: for the OpenGL API man pages
                           mesa-vdpau: for accelerated video playback
                           libva-mesa-driver: for accelerated video playback
Benötigt von             : cogl  glmark2  gst-plugins-base-libs  gtk3  libglvnd  wlroots
Optional für             : Nichts
In Konflikt mit          : mesa-libgl
Ersetzt                  : mesa-libgl
Installationsgröße       : 56,60 MiB
Packer                   : Unknown Packager
Erstellt am              : So 28 Aug 2022 19:11:47 CEST
Installiert am           : So 28 Aug 2022 19:33:11 CEST
Installationsgrund       : Installiert als Abhängigkeit eines anderen Pakets
Installations-Skript     : Nein
Verifiziert durch        : Nichts
```

```
k_ronny@archlinux ~ > glxinfo | grep OpenGL    
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL core profile version string: 4.3 (Core Profile) Mesa 22.1.7
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.3 (Compatibility Profile) Mesa 22.1.7
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.1.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```


Anyway, since it is now enabled in linux-aarch64 5.19.4-1, I close this PR.

**Pull request closed without merging**
