### PR TITLE
core/glibc: fix no such file when building

### PR DESCRIPTION
**Pull request by mio-19**

### CODE REVIEW

**Review by joske — APPROVED** [review]
this worked for me

**Comment by mkurz** [comment]
@graysky2 Any reason to hold this back?

**Comment by graysky2** [comment]
I do not maintain the toolchain/cannot merge.

**Comment by mkurz** [comment]
@kmihelich This should be ready, can you please take a look?

**Comment by graysky2** [comment]
You will probably want to follow the [contributing guidelines](https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md).

**Comment by mkurz** [comment]
@mio-19 Can you please squash your commits, so this pull request just contains one single commit? Thanks!

**Comment by mio-19** [comment]
> @mio-19 Can you please squash your commits, so this pull request just contains one single commit? Thanks!

done

**Comment by mkurz** [comment]
@kmihelich This PR should now be good to go. Any objections?

**Comment by mkurz** [comment]
@kmihelich How about merging this pull request? Seems legit and also should fulfill all requirements. Thanks!

**Comment by solskogen** [comment]
I think this should be merged instead: https://github.com/archlinuxarm/PKGBUILDs/pull/2021

**Comment by graysky2** [comment]
This is no longer relevant

**Comment by mkurz** [comment]
We are now stuck on glibc 2.39 but 2.40 is out since quite a while. Can someone take a look why we don't get the update?

**Pull request closed without merging**
