### PR TITLE
alarm/kodi-rbp to 17.3-4

### PR DESCRIPTION
**Pull request by graysky2**

### CODE REVIEW

**Comment by kmihelich** [comment]
Did you ensure that this package actually builds this time on all relevant architectures?  Or are we going to have a repeat of last time with you submitting a broken package, whining on the forum about your broken submission, and you doing nothing to fix it?

**Comment by graysky2** [comment]
> Did you ensure that this package actually builds this time on all relevant architectures?

Yes, builds fine on armv7h.  I do not have armv6h hardware any more so cannot verify it.

**Comment by kmihelich** [comment]
Not having the hardware is not an excuse.  When you test your submission, as required per the rules of contributions, this PR can be merged.

**Comment by graysky2** [comment]
I would be glad to verify that it builds for armv6h.  I am assuming that I need devtools-alarm to do this via `mkarchroot` but am not seeing a corresponding `/usr/share/devtools/makepkg-armv6h.conf` file.  Is my assumption incorrect?

**Comment by graysky2** [comment]
I just extracted the ArchLinuxARM-rpi-latest tarball and used arch-chroot  + distcc therein from my RPi3.  The armv6h package builds successfully as well.

FYI - This PR is just mirroring [this](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/kodi&id=0e12d5c669125c921b66773417fa05170a424d13) Arch upstream update to [community]/kodi.

**Pull request merged**
