### PR TITLE
linux-aarch64: Generate device tree blobs with symbols

### PR DESCRIPTION
**Pull request by lassebm**
This is required to support applying device tree overlays in U-Boot. Tested with `rpi-poe-overlay.dtb` from the Raspberry Pi Foundation tree, on RPi3B+.

### CODE REVIEW

**Comment by lassebm** [comment]
@kmihelich Care to elaborate?

**Comment by lassebm** [comment]
@kmihelich If it was closed due not squashing commits, I will squash and create a new PR. I'll need a hint from you.

**Comment by lassebm** [comment]
@kmihelich If it was closed due to not squashing commits, I will squash and create a new PR. I need a hint.

**Comment by Holzhaus** [comment]
@lassebm in my experience @kmihelich usually closes PRs if they do not meet all requirements outlined in [`CONTRIBUTING.md`](CONTRIBUTING.md).

**Comment by lassebm** [comment]
@Holzhaus Yes, exactly. I can only really see the missed squashing as being the reason for a silent close.

**Comment by lassebm** [comment]
@kmihelich Can I get a word from you whether or not I should create a new squashed PR? Thanks.

**Comment by kmihelich** [comment]
Just follow the rules.

**Comment by lassebm** [comment]
@kmihelich I already squashed and force pushed to the branch. Are you able to reopen this PR?

**Comment by kmihelich** [comment]
Nope.

**Pull request closed without merging**
