### PR TITLE
community/mythtv: Fix libudfread compilation error

### PR DESCRIPTION
**Pull request by PlanetEater**
Fix the following error:
udfread.c:104:3: error: #error no atomic operation support

Inspired by mythtv/external/libmythbluray/libmythbluray.pro.
Also, the upstream tarball seems to have changed, so its checksum had to be updated.

### CODE REVIEW

**Comment by kmihelich** [comment]
Don't increment pkgrel.

**Comment by PlanetEater** [comment]
Done.

**Comment by moonman** [comment]
Please read https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
mythtv *is* an upstream package 
what I can see wrong so far:
1. commits not squashed
2. pkgrel needs to be incremented by a decimal number, and not a whole number
3. no description of what you did in the header of PKGBUILD (add your changes under ALARM: Kevin Mihelich... following his example)
Again, check CONTRIBUTING.md in case I missed something.

**Comment by PlanetEater** [comment]
Seems like I will have to create a new pull request to squash commits, so I'm closing this one.

**Comment by moonman** [comment]
Seriously, read CONTRIBUTING.md it's all there (including that you do *not* need to open a new PR)

**Pull request closed without merging**
