### PR TITLE
add alarm/uboot-nanopct4

### PR DESCRIPTION
**Pull request by a-andre**

### CODE REVIEW

**Comment by kmihelich** [comment]
Not a supported system.

**Comment by a-andre** [comment]
@kmihelich Where can I find information about what's necessary to make it a supported system? I couldn't find anything in the forum. Thanks.

**Comment by tmountain** [comment]
@a-andre I have a question about this PR. Is there a way I can contact you directly?

**Comment by a-andre** [comment]
@tmountain you can use the issue or discussion board of https://github.com/a-andre/PKGBUILDs.

**Pull request closed without merging**
