### PR TITLE
Add support for Broadcom's VC4 hardware to mesa

### PR DESCRIPTION
**Pull request by greysAcademicCode**

### CODE REVIEW

**Comment by WarheadsSE** [comment]
My only immediate concern is that this would add this to all 4 architectures, where the VC4 is only applicable for v6/v7

**Comment by greysAcademicCode** [comment]
Should I put an if statement around it that checks the architecture?

**Comment by WarheadsSE** [comment]
Perhaps something simpler, like a conditional filling a variable that fills the end of the line

**Comment by greysAcademicCode** [comment]
You're thinking of a line like `[ $CARCH == "armv7h" -o $CARCH == "armv6h" ] && VC4=',vc4'`?

**Comment by greysAcademicCode** [comment]
making new PR for this

**Pull request closed without merging**
