### PR TITLE
alarm/{firmware-imx,imx-vpu,libfslvpuwrap} update to 3.10.31-beta release

### PR DESCRIPTION
**Pull request by CrawX**
This updates the freescale libraries imx-vpu and libfslvpuwrap to the newese -beta release.
It also updates the firmware needed for the vpu to the newest -beta release.

I've been running this for quite some time now and I have had better results with those beta versions than I have ever had with the ga ones. While I have not experienced any performance changes, they seem to be much more stable.

I suggest to merge this along with / before archlinuxarm/PKGBUILDS#1040.

Happy holidays!

### CODE REVIEW

**Comment by moonman** [comment]
Looks good to me. Anyone against merging this?

**Comment by kmihelich** [comment]
Does kodi-imx need a rebuild for this?

**Comment by CrawX** [comment]
As seen here https://github.com/Freescale/meta-fsl-arm/compare/24d3ed639a...ce65e1ed40, there are already newer versions of the libraries available than the ones I packaged in this pull request.

I have not tested this newer versions but I'm happy to update this PR (or create a new one) incorporating the new libraries. Except for the kernels and gpu-viv-bin-mx6q we should always be using the most recent versions.

**Comment by pepedog** [comment]
I have to chop down a forest before I can look at this (no kidding)

**Comment by kmihelich** [comment]
Sure, go ahead and update it.

**Comment by CrawX** [comment]
Superseded by #1169 .

**Pull request closed without merging**
