### PR TITLE
Enable IPsec in kernel

### PR DESCRIPTION
**Pull request by bl0ndynek**
As you mention on forum: 
http://archlinuxarm.org/forum/viewtopic.php?f=31&t=8339
I create pull request to enable IPsec in kernel by default.

### CODE REVIEW

**Comment by kmihelich** [comment]
*Why* does this need to be built-in? Do the modules not work?

**Comment by pepedog** [comment]
I am guessing you manually edited this file, as bfq patches are not available.

**Comment by bl0ndynek** [comment]
I enable it in kernel.

@kmihelich could you tell me what module should I load to enable it? it could be enough.

**Comment by kmihelich** [comment]
Each CONFIG option has documentation that is easily found, and which specifies what its module name will be.  This documentation is not me.

**Pull request closed without merging**
