### PR TITLE
alarm/kodi-imx: missing dependency fixed

### PR DESCRIPTION
**Pull request by dklementjev**
Package: alarm/kodi-imx 
Architecture: armv7
Device: Cubox-i i4P-300-D

What it isn't doing: Kodi [refuses to start](https://github.com/archlinuxarm/PKGBUILDs/pull/1221#issuecomment-125694636), complaining about missing `libg2d.so.0.8`

What it should be doing: Kodi started successfully, home screen rendered on TV

Steps to reproduce: make sure `gpu-viv-g2d` is not installed, install `kodi-imx`, then start `kodi` service

### CODE REVIEW

**Comment by WarheadsSE** [comment]
Provide a description.

**Comment by dklementjev** [comment]
PR description updated

**Comment by WarheadsSE** [comment]
It is still incomplete. Multiple changes that need to be made are not present.

Does this dependency's missing state cause malfunction?

**Comment by dklementjev** [comment]
Yes, Kodi fails to start:
```
# systemctl status kodi
● kodi.service - Starts an instance of Kodi
   Loaded: loaded (/usr/lib/systemd/system/kodi.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2015-07-28 20:51:51 MSK; 6s ago
  Process: 8020 ExecStopPost=/bin/sh -c echo 1 > /sys/class/graphics/fbcon/cursor_blink (code=exited, status=0/SUCCESS)
  Process: 8004 ExecStart=/usr/bin/kodi-standalone -l /run/lirc/lircd (code=exited, status=0/SUCCESS)
  Process: 8001 ExecStartPre=/bin/sh -c echo 0 > /sys/class/graphics/fbcon/cursor_blink (code=exited, status=0/SUCCESS)
 Main PID: 8004 (code=exited, status=0/SUCCESS)

Jul 28 20:51:50 arch-imx6 systemd[1]: Starting Starts an instance of Kodi...
Jul 28 20:51:51 arch-imx6 systemd[1]: Started Starts an instance of Kodi.
Jul 28 20:51:51 arch-imx6 kodi-standalone[8004]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libg2d.so.0.8: cannot open shared object file: No such file or directory
Jul 28 20:51:51 arch-imx6 kodi-standalone[8004]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libg2d.so.0.8: cannot open shared object file: No such file or directory
Jul 28 20:51:51 arch-imx6 kodi-standalone[8004]: /usr/lib/kodi/kodi.bin: error while loading shared libraries: libg2d.so.0.8: cannot open shared object file: No such file or directory
Jul 28 20:51:51 arch-imx6 kodi-standalone[8004]: /usr/bin/kodi --standalone -l /run/lirc/lircd has exited uncleanly 3 times in the last 0 seconds.
```

After `pacman -S gpu-viv-g2d`:
```
# systemctl status kodi
● kodi.service - Starts an instance of Kodi
   Loaded: loaded (/usr/lib/systemd/system/kodi.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2015-07-28 20:52:32 MSK; 8s ago
  Process: 8020 ExecStopPost=/bin/sh -c echo 1 > /sys/class/graphics/fbcon/cursor_blink (code=exited, status=0/SUCCESS)
  Process: 8029 ExecStartPre=/bin/sh -c echo 0 > /sys/class/graphics/fbcon/cursor_blink (code=exited, status=0/SUCCESS)
 Main PID: 8032 (kodi-standalone)
   CGroup: /system.slice/kodi.service
           ├─8032 /bin/sh /usr/bin/kodi-standalone -l /run/lirc/lircd
           ├─8034 /bin/sh /usr/bin/kodi --standalone -l /run/lirc/lircd
           └─8036 /usr/lib/kodi/kodi.bin --standalone -l /run/lirc/lircd

Jul 28 20:52:36 arch-imx6 kodi-standalone[8032]: libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by WarheadsSE** [comment]
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md

**Comment by dklementjev** [comment]
PR description updated, pkgrel bumped

**Pull request merged**
