### PR TITLE
linux-am33x: make linux-firmware optional

### PR DESCRIPTION
**Pull request by ilpianista**
In Arch Linux, `linux-firmware` is optional [since 5.3.2.arch2-1](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=f1c97a49a09b0fd8d7d1c3f6e8e635ef45974373).

May we reflect the same change here?

### CODE REVIEW

**Comment by kmihelich** [comment]
I'm guessing you've already checked that it's not using anything from there?

**Comment by ilpianista** [comment]
Yes, I removed it and I'm still able to login via eth. It doesn't have WiFi nor Bluetooth, so I don't think there's anything else to check.

**Comment by kmihelich** [comment]
Your comment brought up a good point.  I'll check the BeagleBones with wireless (and no ethernet) later today to make sure they're not pulling from that firmware.

**Comment by ilpianista** [comment]
@kmihelich so?

**Comment by kmihelich** [comment]
Sorry for the delay.  Beaglebone wireless does use firmware from this package, so not a good idea to remove it.

**Pull request closed without merging**
