### PR TITLE
Update to kernel code and config:

### PR DESCRIPTION
**Pull request by btv**
- Added BFQ patches to the patching process
- Added messages indicating the patches being applied
- Changed config so that BFQ is the new default io scheduler.

Have had this running on my own odroid-c1 for 2 days without issue. Performance does feel more responsive, but I don't have any formal proof.

### CODE REVIEW

**Comment by moonman** [comment]
LGTM

**Comment by btv** [comment]
Do you want me to resubmit the patch since the files have changed?

**Comment by btv** [comment]
rebased and updated for pkgrel3 to 4.

**Comment by moonman** [comment]
Please read how to properly contribute: https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md
Specifically "Squash commits" and "Descriptive titles" i.e. squash everything into one commit and specify which package is being changed in the title.

**Pull request closed without merging**
