### PR TITLE
alarm/kodi-odroid to 17.6

### PR DESCRIPTION
**Pull request by frol**
Tested on my Odroid U3

P.S. I couldn't get CMake configs working with Mali-EGL just yet.

### CODE REVIEW

**Comment by frol** [comment]
@archlinuxarm I wonder why while this PR was merged half a year ago, the package in the repo is still outdated (17.3 instead of 17.6).

**Comment by frol** [comment]
Oh, it seems that the cause is the missing `cwiid`. I will send a PR.

**Comment by heikojansen** [comment]
@frol could you send that PR you mention in your last comment? I'm trying to install Kodi on my Odroid U2 but the currently available package (v17.3) contains a kodi binary that is linked to a few libraries which are no longer available (like libcdio 1.6 or mysqlclient 18) and thus won't work.
If all that is necessary is the removal of the cwiid dependency I can send in a PR myself but if it's more involved I do not know if I can be of any help.

And as a related question: is it true that an update to kodi v18 for this package would require https://github.com/Owersun/xbmc/ to be updated first?

**Comment by frol** [comment]
> And as a related question: is it true that an update to kodi v18 for this package would require https://github.com/Owersun/xbmc/ to be updated first?

Yes, that is right, and I have no control over it.

> could you send that PR you mention in your last comment?

Yes, I can, but the latest version available in the Owersun repo is 18.0-rc3. Would you be interested in giving the package a try before it is merged into the archlinuxarm repo?

**Comment by heikojansen** [comment]
> Yes, I can, but the latest version available in the Owersun repo is 18.0-rc3. Would you be interested in giving the package a try before it is merged into the archlinuxarm repo?

Maybe first get a v17.6 build out of the door from the "Krypton" branch at https://github.com/Owersun/xbmc/ ? Hopefully that would just work?!?

Regarding v18. Well, yes, I am interested. But to be honest I'm new to _both_ ArchLinux _and_ Kodi. Am normally using openSUSE; had Debian on my Odroid U2 so far but never got to know it very good. Have tested Kodi only for a few hours running on a RasPi using LibreELEC.  So I don't know if I'd be of much use... Still, I'm willing to install it (especially since there's no working installation I could destroy). And I can test a few things like music library, DLNA, picture browsing and maybe some apps. Don't have a movie library etc., though.

**Comment by frol** [comment]
I will work on PR and package tomorrow. Hopefully, it will go smoothly.

**Comment by frol** [comment]
@heikojansen Please, try these two versions:

1. It is my attempt to rebase PKGBUILD from kodi-c1:

  * The patch: https://netatopa.prostoksi.com/kodi-odroid-17.6-3-PGKBUILD.patch
  * https://netatopa.prostoksi.com/kodi-odroid-17.6-3-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-dev-17.6-3-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-eventclients-17.6-3-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-tools-texturepacker-17.6-3-armv7h.pkg.tar.xz

2. This is just the original PKGBUILD with removed cwiid:

  * The patch: https://netatopa.prostoksi.com/kodi-odroid-17.6-2-PGKBUILD.patch
  * https://netatopa.prostoksi.com/kodi-odroid-17.6-2-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-dev-17.6-2-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-eventclients-17.6-2-armv7h.pkg.tar.xz
  * https://netatopa.prostoksi.com/kodi-odroid-tools-texturepacker-17.6-2-armv7h.pkg.tar.xz

I believe, you only need `kodi-odroid-17.6-*-armv7h.pkg.tar.xz` package, but I share all the produced archives.

**Comment by heikojansen** [comment]
OK, so I installed and tested both builds.

In both packages the kodi.bin is linked to `libmysqlclient.so.18` which I do not have and have found no way of installation for. I do have `/usr/lib/libmysqlclient.so` though, provided by `extra/mariadb-libs` (10.3.12-5).
In the end I added a symlink from `/usr/lib/libmysqlclient.so.18` to `/usr/lib/libmysqlclient.so` to satisfy the dependency...

I could not get the second build (original minus cwiid) to run. It kept crashing and dumping cores.

I was able to get the first build running. Since I do not have a desktop env on my U2 I replaced `/usr/lib/systemd/system/kodi.service` with what is provided in [https://github.com/graysky2/kodi-standalone-service/blob/master/init/kodi.service](https://github.com/graysky2/kodi-standalone-service/blob/master/init/kodi.service) and then could start Kodi via `systemd start kodi`.

Those parts I could test (music library and playback, some add-ons for video streaming, DLNA) worked. :-)

Only negative thing is that the whole thing felt somewhat sluggish. I had tried Kodi (some 18.beta) briefly on a RasPi 1 Model B and remember it feeling OK so given that the Odroid U2 is rather more powerful I expected even smoother operation. However, even with no video or audio playing `top` shows the Kodi process using more than 300% CPU usage (the U2 has 4 cores).
The UI is usable and music plays without interruptions but given that my U2 is passively cooled I feel just a little uncomfortable...  
Given that I hope for an update to v18 I do not think it makes much sense trying to debug this with v17.6 any more unless you have some idea what could cause this.
Should it still apply to v18 I can provide `strace` data etc.

**Comment by frol** [comment]
@heikojansen Thanks a lot for the testing! I only have U3 board and Kodi did not use much CPU unless I watch some sorts of videos (I believe, it automatically fallbacks to CPU decoding). I cannot really test Kodi on my U3 anymore since I don't have a display / TV at the moment.

I will send a PR with the rebased PKGBUILD config shortly.

**Comment by heikojansen** [comment]
> Yes, I can, but the latest version available in the Owersun repo is 18.0-rc3. Would you be interested in giving the package a try before it is merged into the archlinuxarm repo?

@frol : https://github.com/Owersun/xbmc/tree/master was updated to Kodi v18.1-rc1 
If you'd build test packages based on it I'd do my best to test them. 
If you'd prefer to wait for the repo to be updated after a final v18.1 release that's of course completely fine - thanks to your effort I have a working v17.6 and no pressing need to update... ;-)

**Comment by frol** [comment]
@heikojansen I will give it a try. Thanks for the heads up!

**Pull request merged**
