### PR TITLE
Updated linux-raspberrypi4 with aarch64 support.

### PR DESCRIPTION
**Pull request by njordan64**
Added support for building linux-raspberrypi4 under aarch64.

### CODE REVIEW

**Comment by kmihelich** [comment]
aarch64 support is provided by linux-aarch64.

**Comment by Titaniumtown** [comment]
I thought linux-aarch64 doesn't have all the drivers and patches for it to be stable and fast on a raspberry pi.

**Comment by njordan64** [comment]
Is linux-aarch64 suitable for a Raspberry Pi 4?

**Comment by Titaniumtown** [comment]
Not that I know of, afaik there are still a TON of stuff to be added to the mainline kernel for proper support for the raspberry pi 4.

**Comment by njordan64** [comment]
There is this, but it would sure be nice to have everything in one place?

https://aur.archlinux.org/packages/linux-raspberrypi4-aarch64/

**Comment by Titaniumtown** [comment]
It would be nice to have it all in one place. I also have my own PKGBUILDs for each branch here: https://github.com/Titaniumtown/raspi4_pkgbuilds

**Comment by njordan64** [comment]
@kmihelich A package like this is needed. linux-aarch64 does not boot on a Raspberry Pi4. We need a path forward. The RPI4 supports aarch64. How can we get an aarch64 kernel in Arch Linux Arm?

I can understand not liking the changes I had, but how can we get a bootable aarch64 kernel in Arch Linux Arm for Raspberry Pi4? Would you like a new package? Should I rework the changes that I had?

**Comment by ivangrynkoring** [comment]
@njordan64 actually linux-aarch64 works fine with RPI4
`[alarm@raspberrypi ~]$ uname -a
Linux raspberrypi 5.8.7-1-ARCH #1 SMP Sat Sep 5 22:30:43 UTC 2020 aarch64 GNU/Linux`
The only thing i'm missing in this kernel is CONFIG_COMPAT option, which , I guess, should allow to run armv7h binaries.

**Comment by ivanich** [comment]
@njordan64 actually linux-aarch64 works fine with RPI4
[alarm@raspberrypi ~]$ uname -a Linux raspberrypi 5.8.7-1-ARCH #1 SMP Sat Sep 5 22:30:43 UTC 2020 aarch64 GNU/Linux
The only thing i'm missing in this kernel is CONFIG_COMPAT option, which , I guess, should allow to run armv7h binaries.

**Comment by njordan64** [comment]
@ivanich You are correct. Apparently I needed to update some configs. I don't have Xorg running yet, but that is probably something on my side.

**Comment by Titaniumtown** [comment]
One MAJOR thing that hasn't been mainlined relating to the raspberry pi 4: 

https://www.phoronix.com/scan.php?page=news_item&px=RPi4-Display-Linux-5.10-Coming

> Raspberry Pi 4 VC4 Support Coming With Linux 5.10

Graphics are pretty important.

**Pull request closed without merging**
