### PR TITLE
Fix kodi-rbp-git crash on startup

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Use CX11 ABI

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
@kmihelich can you please merge this?

**Comment by pepedog** [comment]
This won't automatically build and end up in repo, release needs bumping for that.

**Comment by julianxhokaxhiu** [comment]
Who should we bump then?

**Comment by moonman** [comment]
Since the forum is not available ATM, I'll reply here as well. This will not work. 
kodi stable for multiple devices was built manually using gcc5.1. Then kmihelich, once again, manually pushed it to the repos. kodi-rbp-git is a low priority package and seeing how many rebuilds it requires it will not be rebuilt manually every time. That is until the problem with gcc > 5.1 is identified and fixed.

Your proposed fix will not have any effect with gcc 5.3 since gcc 5.3 already defaults to the new abi. It was indroduced for an older gcc 5.1 package which defaulted to the old abi.

**Comment by julianxhokaxhiu** [comment]
Thank you very much for the explanation :)

**Pull request closed without merging**
