### PR TITLE
Upgrade alarm/kodi-c2 to the last upstream version at github.com/owersun/xbmc

### PR DESCRIPTION
**Pull request by fuzzysloth**
The upstream commit 1aa79fd7894a2880a5f12a5c95f670b9987ebb1c from Owersun/xbmc fixes CBitstreamConverter instance initialization.

Please note that linux-odroid-c2 starting from 3.14.79-25 breaks hardware accelerated video decoding in Kodi which relies upon aml-libs-c2. Since I don't know how to fix that compatibility issue - I've proposed a temporary solution here: https://archlinuxarm.org/forum/viewtopic.php?f=5&t=11855.
The history of the compatibility problem: https://archlinuxarm.org/forum/viewtopic.php?f=15&t=11777

### CODE REVIEW

**Comment by Taijian** [comment]
When I tried compiling this, I needed to change `patch -Np0 -i ../../FTPParse_std_string.patch` to `patch -Np0 -i ../FTPParse_std_string.patch` in order for makepkg to find the patch.

**Comment by fuzzysloth** [comment]
> When I tried compiling this, I needed to change patch -Np0 -i ../../FTPParse_std_string.patch to patch -Np0 -i ../FTPParse_std_string.patch in order for makepkg to find the patch.

@Taijian, I cannot confirm the issue. Can you check that you (or me) run makepkg in the right working directory? What I do is cd to alarm/kodi-c2 directory of the local repo and when I run "makepkg -so" I get the output that looks OK:
```
==> Making package: kodi-c2 17.3-2 (Sat Jul 22 21:52:48 CEST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading 1aa79fd7894a2880a5f12a5c95f670b9987ebb1c.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154    0   154    0     0    348      0 --:--:-- --:--:-- --:--:--   349
100 55.7M    0 55.7M    0     0  7751k      0 --:--:--  0:00:07 --:--:-- 8034k
  -> Found kodi_permissions.conf
  -> Found kodi.service
  -> Found polkit.rules
  -> Found 99-odroid.rules
  -> Found FTPParse_std_string.patch
==> Validating source files with sha256sums...
    1aa79fd7894a2880a5f12a5c95f670b9987ebb1c.tar.gz ... Passed
    kodi_permissions.conf ... Passed
    kodi.service ... Passed
    polkit.rules ... Passed
    99-odroid.rules ... Passed
    FTPParse_std_string.patch ... Passed
==> Extracting sources...
  -> Extracting 1aa79fd7894a2880a5f12a5c95f670b9987ebb1c.tar.gz with bsdtar
==> Starting prepare()...
patching file xbmc/filesystem/FTPParse.cpp
==> Sources are ready.
```
The patch command is being executed in alarm/kodi-c2/src/xbmc-${_commit} directory while the patch file itself is located in alarm/kodi-c2 directory - hence "../../" prefix.

**Comment by fuzzysloth** [comment]
@kmihelich: Can you please provide some motivation of closing this one? Taking my previous comment into account.

**Comment by fuzzysloth** [comment]
@kmihelich: Few other notes. I already understood that I violated at least "one package per request" policy.
Can you please point me how I can make a better PR?
What I aimed in this PR was:
- do what PR description says
- try to fix HW acceleration in Kodi by discarding pre-build shared libraries in aml-libs-c2 and re-build them with gcc 7.1.1
- fix Kodi build problem which was presumably caused by new version of pcre (FTPParse_std_string.patch)

While my initial assumption was that Kodi update and rebuild would fix broken HW decoding - @mk-fg pointed me that the issue is caused by re-building linux-odroid-c2 with gcc 7.1.1 rather than by the changes made in during linux-odroid-c2 update from 3.14.79-24 to 3.14.79-25.

Whatever decision you will make regarding my contribution - please keep in mind that:
- new Kodi build fails without patching xbmc/filesystem/FTPParse.cpp
- AMLogic HW-accelerated decoding is still broken with linux-odroid-c2 version 3.14.79-25 and onwards.

**Pull request closed without merging**
