### PR TITLE
core/linux-aarch64-rc to 5.17.rc8-2

### PR DESCRIPTION
**Pull request by tech10**
This takes the relevant speakup configuration from linux-rpi and places it within linux-aarch64-rc. I have tested this on a Raspberry Pi 4B. This successfully compiles and adds Speakup support as modules, to either be loaded or not, depending on how someone might choose to use it.

### CODE REVIEW

**Comment by graysky2** [comment]
See third bullet.  You also did not bump the pkgrel nor update the checksums.

https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md

**Comment by tech10** [comment]
@graysky2 I did miss that, thanks. This should be updated now, as requested.

**Comment by graysky2** [comment]
> One package per request. PRs must be for a single package only. A PR addressing multiple packages without merit risks having a delayed merge or being closed.

**Comment by tech10** [comment]
@graysky2 I've decided to focus on the rc release for this one, it should be out of rc status soon enough anyway.

**Pull request merged**
