### PR TITLE
[odroid-c1] Add udev rules to fix /dev/am* permissions

### PR DESCRIPTION
**Pull request by Holzhaus**
This fixes permissions for the /dev/am* devices on ODROID-C1. I hope this is the right package to put them into (if not, please tell me which packe this belongs to and I'll open a new PR).

I tested the udev rules on my C1 and they work fine.

Related forum thread: [http://archlinuxarm.org/forum/viewtopic.php?f=63&t=8348](http://archlinuxarm.org/forum/viewtopic.php?f=63&t=8348)

### CODE REVIEW

**Comment by pepedog** [comment]
I don't think this belongs in a kernel package. What about one of the alarm/Odroid-c1- packages?

**Comment by Holzhaus** [comment]
What do you think about [alarm/aml-libs-c1](https://github.com/archlinuxarm/PKGBUILDs/tree/master/alarm/aml-libs-c1)?

**Comment by kmihelich** [comment]
This would make more sense in aml-libs-c1, since you need those drivers to use the devices anyway.

**Comment by Holzhaus** [comment]
Ok, this PR now refers to the alarm/aml-libs-c1 package.

**Pull request merged**
