### PR TITLE
kodi-rbp-git to 16.0a4-Jarvis

### PR DESCRIPTION
**Pull request by phedoreanu**
Commented "make -j1".

### CODE REVIEW

**Comment by kmihelich** [comment]
Learn to use git and GitHub; stop closing and opening PRs for the same thing.

**Comment by phedoreanu** [comment]
I wanted to squash, but the commits were in the reverse order and I don't know how to rebase and change the parent, so I did a `push -f`. Sorry for repetition.

**Comment by moonman** [comment]
Have you tested this? Why is bootstrap completely commented?

**Comment by phedoreanu** [comment]
Yes, I have tested it with `-j5`. Switched back to `-j1`.

**Pull request merged**
