### PR TITLE
config changes to more fully support iwd (iNet wireless daemon)

### PR DESCRIPTION
**Pull request by gearhead**
iwd is supported in the current kernel build, but these small changes add more features of iwd are supported. iwd is developed by intel, but the RPi brcmfmac driver is now supported by iwd in ap mode as well as station mode. The NLMON module is required to get iwd dev team support. The changes to the armv7 config map directly onto the armv6 config as well.

### CODE REVIEW

**Comment by graysky2** [comment]
Your PR violates several [rules](https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md).

**Comment by gearhead** [comment]
sorry. I will fix it.

**Comment by gearhead** [comment]
Actually, I don't know how to fix it... I have added another commit and
cannot delete the new commit to fix the previous one.
As I read it, I messed up by not upping the pkgrel to 4 and the 2 commits
need to be squashed to 1. What other rules have I violated?

Can this be done in github, or do I need the cli to do it. It may be best
to delete this and start over.

**Comment by gearhead** [comment]
I messed this up royally. I am closing, deleting and starting over. Sorry for the intrusion.

**Comment by graysky2** [comment]
https://github.com/archlinuxarm/PKGBUILDs/commit/06a351024bff49300f160f6f93810ada8643d3ca
https://github.com/archlinuxarm/PKGBUILDs/commit/aff5fc4e14ea1ab266fce00ee6320db39ac3821b

**Pull request closed without merging**
