### PR TITLE
add alarm/kodi-c2-17.0rc2

### PR DESCRIPTION
**Pull request by phedoreanu**
```
------------------------
  Kodi Configuration:
------------------------
  Kodi Version:	17.0-RC2
  git Rev.:	Unknown
  Debugging:	No
  Profiling:	No
  Optimization:	Yes
  SWIG Available:	Yes
  JRE Available:	Yes
  Doxygen Available:	Yes
  Crosscomp.:	No
  target ARCH:	aarch64
  target CPU:	
  OpenGLES:	Yes
  ALSA:		Yes
  DBUS:		Yes
  VDPAU:	No
  VAAPI:	No
  OpenMax:	No
  X11:		No
  Bluray:	Yes
  XSLT scrapers:	Yes
  TexturePacker:No
  MID Support:	No
  ccache:	Yes
  ALSA Support:	Yes
  PulseAudio:	Yes
  Google Test Framework Configured:	Yes
  Avahi:	Yes
  mDNSEmbedded:	No
  Non-free:	Yes
  MySQL:	Yes
  Webserver:	Yes
  libssh support:	Yes
  libsmbclient support:	Yes
  libnfs client support:Yes
  AirPlay support:	Yes
  AirTunes support (libshairplay):	Yes
  UPnP support:		Yes
  Optical drive:	Yes
  libudev support:	Yes
  libusb support:	No
  libcec support:	Yes
  lcms2 support:	Yes
  libbluetooth support:	Yes
  libcap support:	Yes
  additional players:	No
  additional codecs:	Yes, amcodec
  Odroid Hybris support:	No
  prefix:	/usr
------------------------
```

### CODE REVIEW

**Comment by graysky2** [comment]
Would be nice to have an official kodi for the C2.  Curious why you have chosen the x11 driver and not the fb one.

**Comment by phedoreanu** [comment]
Thanks!
1. Reverted to `odroid-c2-libgl-fb` driver.
2. Moved `libcec` to optdeps.
3. Removed `ccache` from makedeps.

**Comment by graysky2** [comment]
@phedoreanu - Does this build and give a working binary?  Coredumps for me.

```
[12268.047923] kodi.bin[19674]: undefined instruction: pc=000000000083390c
[12268.052547] Code: f946e821 b4000441 91002000 52800021 (b8e10001) 
[12268.064870] systemd-coredump[19675]: [/etc/systemd/coredump.conf:15] Failed to parse storage setting, ignoring: volatile
[12268.154510] systemd-coredump[19676]: [/etc/systemd/coredump.conf:15] Failed to parse storage setting, ignoring: volatile
[12268.164576] systemd-coredum[19676]: syscall 285
[12268.168483] Code: aa0503e4 aa0603e5 aa0703e6 d4000001 (b13ffc1f) 
[12268.174036] CPU: 2 PID: 19676 Comm: systemd-coredum Not tainted 3.14.79-14-ARCH #1
[12268.181595] task: ffffffc05bf1e000 ti: ffffffc05b25c000 task.ti: ffffffc05b25c000
[12268.189023] PC is at 0x7f9ee743e4
[12268.193082] LR is at 0x7f9f058aec
[12268.197133] pc : [<0000007f9ee743e4>] lr : [<0000007f9f058aec>] pstate: 20000000
[12268.202925] sp : 0000007fcd45d2b0
[12268.207948] x29: 0000007fcd45d2b0 x28: 0000000080000000 
[12268.215140] x27: 0000000000000001 x26: 0000000000000001 
[12268.220439] x25: 0000000000000001 x24: 00000000ffffffff 
[12268.225598] x23: 0000000080000000 x22: 0000000000000007 
[12268.230796] x21: 0000000000000006 x20: 0000000000004000 
[12268.236031] x19: 0000005573a8b000 x18: 0000000000000000 
[12268.241278] x17: 0000007f9ee743c0 x16: 0000007f9f1bb350 
[12268.246402] x15: 0000000000000000 x14: 0000000000000000 
[12268.251664] x13: 2e39623135316237 x12: 3438656431366131 
[12268.256865] x11: 0000000000000000 x10: aaa8aaaaaa000000 
[12268.262067] x9 : 0000005573aa0dc0 x8 : 000000000000011d 
[12268.267340] x7 : 0000000000000000 x6 : 0000000000000000 
[12268.272591] x5 : 0000000000000000 x4 : 0000000080000000 
[12268.277851] x3 : 0000000000000000 x2 : 0000000000000007 
[12268.283093] x1 : 0000000000000000 x0 : 0000000000000006 
```

**Comment by phedoreanu** [comment]
I think that's why I chose `odroid-c2-libgl-x11`.

**Comment by graysky2** [comment]
> I think that's why I chose odroid-c2-libgl-x11.

I build it as you uploaded it (with odroid-c2-libgl-x11 and it core dumps).  Does it work for you?

**Comment by phedoreanu** [comment]
Yes, with x11. Maybe you tried to build the squashed version (using fb)?

**Comment by graysky2** [comment]
> Yes, with x11. Maybe you tried to build the squashed version (using fb)?

No, I build it unmodified from your original PR.

**Comment by phedoreanu** [comment]
Try `sudo kodi`.

**Comment by graysky2** [comment]
> Try sudo kodi.
Why in the world would I do that?

How exactly are you running kodi?  Are you using a desktop environment?

**Comment by phedoreanu** [comment]
> How exactly are you running kodi? Are you using a desktop environment?
Yes, with LXDE.

**Comment by graysky2** [comment]
What is the output of
`pacman -Qs odroid`

I think the CFLAGS aren't right inthe PKGBUILD.

**Comment by phedoreanu** [comment]
```
$ pacman -Qs odroid
local/aml-libs-c2 r3.ed1d8b8-1
    ODROID-C2 Amlogic Libraries
local/linux-odroid-c2 3.14.79-14
    The Linux Kernel and modules - ODROID-C2
local/odroid-c2-libgl-x11 r6p1-2
    ODROID-C2 Mali driver (X11)
local/uboot-odroid-c2 2015.01-14
    U-Boot for ODROID-C2
local/xf86-video-odroid-c2 0.5-2
    X.org Mali video driver for ODROID-C2
```

**Comment by graysky2** [comment]
OK... for starters, I commented the customized CFLAGS, LDFLAGS and GCC_OPTS you defined replaced all 3 lines with just:
```
LDFLAGS+=" -L/usr/lib/mali-egl"
```

That led to a binary that didn't coredump.  Next I installed lxde xf86-video-odroid-c2.  Once in lxde I see the following indicating that something isn't quite right with the permissions to something... if you are invoking kodi with sudo and it works, that confirm it.

```
ERROR: failed to initialize egl display
ERROR: Failed to find matching visual
```

**Comment by graysky2** [comment]
Regardless of the GCC and CFLAGS, we need to figure out why non-root users cannot run kodi.  I start (this)[http://forum.kodi.tv/showthread.php?tid=302424] thread in the kodi forums.

**Comment by graysky2** [comment]
You need to have libcec in your makedepends or else that won't be detected and built

...are you testing the PKGBUILD (ie it builds and gives a working binary) before you update and push the PR?

**Comment by moonman** [comment]
1. I can't stress this enough: Please read the rules. One PR per package
2. I am not the maintainer, and I'm pretty sure Kevin is not going to maintain this package either so if you are willing to maintain this package going forward please add yourself as the Maintainer

**Comment by phedoreanu** [comment]
>I can't stress this enough: Please read the rules. One PR per package

Sorry. Squashed and created #1432

>I am not the maintainer, and I'm pretty sure Kevin is not going to maintain this package either so if you are willing to maintain this package going forward please add yourself as the Maintainer

Sorry again. Done.

**Comment by phedoreanu** [comment]
Latest binary changelog:
 * removed `X11` in favour of `fb`
 * linked with lastest `aml-libs-c2`
 * added `kodi.service`

**Comment by moonman** [comment]
Looks good to me. Does anyone have any concerns about merging this?

**Comment by Baumfaust** [comment]
Kodi starts on my C2, everything looks fine but playback performance is very low.
Looks like no gpu hardware acceleration maybe?
Can someone confirm this?

**Pull request merged**
