### PR TITLE
fix: bring back cgroup memory

### PR DESCRIPTION
**Pull request by zetxx**
i don't know why is removed anyway, missing of this options prevent docker to limit container memory usage

### CODE REVIEW

**Comment by zetxx** [comment]
was removed in this commit: https://github.com/archlinuxarm/PKGBUILDs/commit/e87bd6d0017baf0a475d43353ee2031e9fd164d7

**Comment by kmihelich** [comment]
https://github.com/raspberrypi/linux/commit/c6e202bcf3aff35075f41ca70a90c89350e1edd6

**Comment by zetxx** [comment]
ok, thanks

**Comment by zetxx** [comment]
did you aware of this: https://github.com/agherzan/meta-raspberrypi/commit/5a3919f89ae8eaf6cf6f04d0c96215d886439155 ?

**Pull request closed without merging**
