### PR TITLE
core/linux-raspberrypi: re-enable BCM_VC_SM

### PR DESCRIPTION
**Pull request by invisiblek**
* This has been fixed in the raspberry pi kernel for multi-platform
  builds.
* Also fix building with a non-clean tree as firmware/brcm
  already exists in that case.

### CODE REVIEW

**Comment by invisiblek** [comment]
Fixed here: https://github.com/raspberrypi/linux/pull/2205

**Comment by invisiblek** [comment]
err, actually. i need to fix the hash for the kernel tar it grabs, hold off a sec

**Comment by kmihelich** [comment]
No, the referenced PR does not fix the issue.  ARMv6 will still be running ARMv7 assembly.

**Comment by invisiblek** [comment]
Huh? It's ifdef'd for v6/v7, unless I'm missing something. The referenced PR fixes the compile error, which I assumed is what caused you to remove this config option in the first place.

**Comment by invisiblek** [comment]
Oh nevermind, I see what you're saying. I have a patch in mind.

**Pull request closed without merging**
