### PR TITLE
Bump linux-odroid-xu3 to current 6.6.y branch

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by polyzen** [comment]
Built in an unclean chroot:
https://pkgbuild.com/~polyzen/linux-odroid-xu3-6.6.30-1-armv7h.pkg.tar.xz
https://pkgbuild.com/~polyzen/linux-odroid-xu3-headers-6.6.30-1-armv7h.pkg.tar.xz

extra-armv7-build doesn't seem to work currently. Any guidance would be appreciated.

**Comment by polyzen** [comment]
@graysky2, any chance this could get a review?

**Comment by graysky2** [comment]
For one, your PR violates the [rules for PR](https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md).  Why are you touching multiple packages?  For two, I don't know why upstream hasn't modified their fork of the kernel.  If it like's their support for the C2, there is not an upgrade path.  Further, I don't have this hardware for testing and if you do, you haven't indicated any functional status of the kernel package on the hardware.

**Comment by polyzen** [comment]
> For one, your PR violates the [rules for PR](https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md).

TIL. Might be good to setup https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

> Why are you touching multiple packages?

Figured linux-armv7 and linux-odroid-xu3 are similar enough that I could help shake the cobwebs off that as well.

Rebasing in preparation of building 6.6.36, and I see you've bumped linux-armv7. Great! Shame you didn't build off the consistency fixes that were in this MR. Can drop the minor consistency fixes for linux-aarch64 as well.

> For two, I don't know why upstream hasn't modified their fork of the kernel. If it like's their support for the C2, there is not an upgrade path.

I don't follow.

> Further, I don't have this hardware for testing and if you do, you haven't indicated any functional status of the kernel package on the hardware.

Ah yes, of course I've been using this for some time now 😄. Output over HDMI seems to work fine still. Anything in particular I should test?

**Comment by polyzen** [comment]
@graysky2 ^

**Comment by polyzen** [comment]
Worth noting that prior to a recent change stemming from mkinitcpio, one could get on with the currently packaged `linux-odroid-xu3 4.14.180` if you had pinned systemd (and NFS and perhaps others) to older versions. Now you would need to add quite a few more packages to `IgnorePkg`.

**Comment by graysky2** [comment]
Please scope the PR to just one PKGBUILD, as your title indicates, `core/linux-odriod-xu3`.

>>  For two, I don't know why upstream hasn't modified their fork of the kernel. If it like's their support for the C2, there is not an upgrade path.

>I don't follow.

I mean that upstream's (hardkernel) fork of the linux kernel has not been updated since 4.14.180.  They pulled this shit with the ODROID-C2 as well.  I want to make sure whatever changes are needed to modernize the kernel are vetted/tested by someone who owns the hardware.

Which branch are thinking is tracking 6.6.y that is specific to this hardware?  Just browsing, I see: https://github.com/hardkernel/linux/tree/odroid-6.6.y but I haven't dug into it looking for specific changes for the XU3.  Have all been mainlined?  Is there a reason to carry a separate kernel for this hardware any more?

**Comment by polyzen** [comment]
> Please scope the PR to just one PKGBUILD, as your title indicates, `core/linux-odriod-xu3`.

Will do, after I try 6.6.36 shortly. Finally setup distcc (thanks for your AUR package btw). I was building under QEMU which takes like a day 😅.

> > > For two, I don't know why upstream hasn't modified their fork of the kernel. If it like's their support for the C2, there is not an upgrade path.
> 
> > I don't follow.
> 
> I mean that upstream's (hardkernel) fork of the linux kernel has not been updated since 4.14.180. They pulled this shit with the ODROID-C2 as well. I want to make sure whatever changes are needed to modernize the kernel are vetted/tested by someone who owns the hardware.
> 
> Which branch are thinking is tracking 6.6.y that is specific to this hardware? Just browsing, I see: https://github.com/hardkernel/linux/tree/odroid-6.6.y but I haven't dug into it looking for specific changes for the XU3. Have all been mainlined? Is there a reason to carry a separate kernel for this hardware any more?

You can see the changes specific to the hardware here:
https://github.com/hardkernel/linux/commits/odroid-6.6.y?author=mdrjr

The only thing I specifically know is needed is a change to the thermal throttling code, as the sensors on the XU3 tend to be faulty.

Learned of this branch after noticing this comment:
https://github.com/hardkernel/linux/pull/435#issuecomment-1992464208

**Comment by graysky2** [comment]
Good that they are keeping their fork active.

Yes, distcc is a good option but a better one particularly for the kernel as it is self-contained is cross compiling on x86_64 assuming you have a powerful box running Arch.  I just updated the [AUR packages](https://aur.archlinux.org/packages?O=0&SeB=nd&K=armv7l) for the cross compiler.  If you'd rather not build them, I can provide you with the versions I built.  Once installed, building is as simple as:
```
% CARCH=armv7h ARCH=arm CROSS_COMPILE=armv7l-unknown-linux-gnueabihf- nice -19 makepkg -sCAfd
```

**Comment by polyzen** [comment]
On July 4, 2024 5:13:19 PM EDT, graysky ***@***.***> wrote:
> Good that they are keeping their fork active.
> 
> Yes, distcc is a good option but a better one particularly for the kernel as it is self-contained is cross compiling on x86_64 assuming you have a powerful box running Arch.  I just updated the [AUR packages](https://aur.archlinux.org/packages?O=0&SeB=nd&K=armv7l) for the cross compiler.  If you'd rather not build them, I can provide you with the versions I built.  Once installed, building is as simple as:
> ```
> % CARCH=armv7h ARCH=arm CROSS_COMPILE=armv7l-unknown-linux-gnueabihf- nice -19 makepkg -sCAfd
> ```
> 
> 
> 

Was wondering how to do that. Thanks, will try it out.

--
Best,
Daniel <https://danielcapella.com>

**Comment by polyzen** [comment]
`cpio` also seems to be a makedep, as the build fails without it, at least with plain makepkg. Have not built in a clean chroot yet.

This MR only touches the linux-odroid-xu3 package now.

**Comment by graysky2** [comment]
Please squash into a single commit.

**Comment by polyzen** [comment]
> Please squash into a single commit.

Done

**Comment by graysky2** [comment]
Thank you, and you can confirm that the latest commit both builds and runs on your hardware?

**Comment by graysky2** [comment]
I think you made a misake ... your recent commit is hitting another package

**Comment by polyzen** [comment]
> Thank you, and you can confirm that the latest commit:
> 
>     * Runs on your hardware with no dmesg regressions or functionality breakage

What stands out so far:

Current kernel:
`kernel: samsung-pinctrl 13400000.pinctrl: Failed to create device link (0x180) with soc`

```
kernel: mali 11800000.gpu: Couldn't find power_model DT node matching 'arm,mali-simple-power-model'
kernel: mali 11800000.gpu: Error -22, no DT entry: mali-simple-power-model.static-coefficient = 1*[0]
kernel: mali 11800000.gpu: Error -22, no DT entry: mali-simple-power-model.dynamic-coefficient = 1*[0]
kernel: mali 11800000.gpu: Error -22, no DT entry: mali-simple-power-model.ts = 4*[0]
kernel: mali 11800000.gpu: Error -22, no DT entry: mali-simple-power-model.thermal-zone = ''
kernel: mali 11800000.gpu: Using configured power model mali-simple-power-model, and fallback mali-simple-power-model
```

Also there less video devices registered:

Current kernel:
```
kernel: s5p-mfc 11000000.codec: preallocated 8 MiB buffer for the firmware and context buffers
kernel: s5p-mfc 11000000.codec: decoder registered as /dev/video0
kernel: s5p-mfc 11000000.codec: encoder registered as /dev/video1
```

Old kernel:
```
kernel: s5p-jpeg 11f50000.jpeg: Linked as a consumer to 11f10000.sysmmu
kernel: iommu: Adding device 11f50000.jpeg to group 3
kernel: s5p-jpeg 11f50000.jpeg: encoder device registered as /dev/video30
kernel: s5p-jpeg 11f50000.jpeg: decoder device registered as /dev/video31
kernel: s5p-jpeg 11f50000.jpeg: Samsung S5P JPEG codec
kernel: s5p-jpeg 11f60000.jpeg: Linked as a consumer to 11f20000.sysmmu
kernel: iommu: Adding device 11f60000.jpeg to group 4
kernel: s5p-jpeg 11f60000.jpeg: encoder device registered as /dev/video32
kernel: s5p-jpeg 11f60000.jpeg: decoder device registered as /dev/video33
kernel: s5p-jpeg 11f60000.jpeg: Samsung S5P JPEG codec
kernel: s5p-mfc 11000000.codec: Linked as a consumer to 11200000.sysmmu
kernel: s5p-mfc 11000000.codec: Linked as a consumer to 11210000.sysmmu
kernel: iommu: Adding device 11000000.codec to group 5
kernel: s5p-mfc 11000000.codec: preallocated 16 MiB buffer for the firmware and context buffers
kernel: (NULL device *): Direct firmware load for s5p-mfc-v8.fw failed with error -2
kernel: s5p_mfc_load_firmware:73: Firmware is not present in the /lib/firmware directory nor compiled in kernel
kernel: s5p-mfc 11000000.codec: decoder registered as /dev/video10
kernel: s5p-mfc 11000000.codec: encoder registered as /dev/video11
kernel: exynos-gsc 13e00000.video-scaler: Linked as a consumer to 13e80000.sysmmu
kernel: iommu: Adding device 13e00000.video-scaler to group 6
kernel: exynos-gsc 13e10000.video-scaler: Linked as a consumer to 13e90000.sysmmu
kernel: iommu: Adding device 13e10000.video-scaler to group 7
```

>     * Triggers the creation of the mkinitcpio image

```
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating module dependencies...
(3/3) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-odroid-xu3.preset: 'default'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k 6.6.36-1-odroid-xu3-ARCH -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
==> Starting build: '6.6.36-1-odroid-xu3-ARCH'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [keyboard]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: '/boot/initramfs-linux.img'
  -> Early uncompressed CPIO image generation successful
==> Initcpio image generation successful
```

> I think you made a misake ... your recent commit is hitting another package

The actual commit is just touching the one package. The compare button is just showing the gnutls changes after I rebased on master again.

**Comment by polyzen** [comment]
cc @mdrjr in case you have any interest/input :D

**Comment by graysky2** [comment]
Not sure, but if this is functional now with a few minor flaws which could be corrected in future releases, I think putting it on a support LTS kernel from a deprecated is more important.

**Comment by bwcknr** [comment]
@graysky2 @polyzen With this package my HC1 refuses to start up, please see attached
[exception.txt](https://github.com/user-attachments/files/16120285/exception.txt)

**Comment by graysky2** [comment]
@polyzen - any thoughts?   missing some HC1 specific commits?

**Comment by polyzen** [comment]
No idea. Sorry to bug you @mdrjr, but you'd know best :p

Seems [this guy built 6.1.90 for his HC1](https://github.com/ffaille/alarm-linux-odroid-xu3/issues/1), but did not mention if it worked. Could try modifying the pkgbuild to build against [6.1.90](https://github.com/hardkernel/linux/commit/1223c9a4f3050eb3beb1202ba317f4071cc85e3b), and see if that works.. It's a [different branch](https://github.com/hardkernel/linux/commits/odroidxu4-6.1.y/).

**Comment by kyak** [comment]
> @graysky2 @polyzen With this package my HC1 refuses to start up, please see attached [exception.txt](https://github.com/user-attachments/files/16120285/exception.txt)

I have the same problem.

Sorry I didn't mention it in https://github.com/ffaille/alarm-linux-odroid-xu3/issues/1. I wanted to have a closer look, but then got swiped away by something else.

**Comment by polyzen** [comment]
Opened an issue upstream https://github.com/hardkernel/linux/issues/437

**Comment by kyak** [comment]
> @kyak - can you install the mainline linux package and see if that boots?
> 
> ```
> pacman -S linux-armv7
> ```

I could, and I will, but not earlier than next week..

**Comment by wickner-consid** [comment]
> @kyak - can you install the mainline linux package and see if that boots?
> 
> ```
> pacman -S linux-armv7
> ```

Updated to linux-odroid-xu3:6.6.40, didn't come up aswell.

Switched to linux-armv7 and it's up and running. Feels a little laggier on the ssh term, but so far all seems to be working over here

**Comment by graysky2** [comment]
@wickner-consid - which hardware please?  XU3?

**Comment by bwcknr** [comment]
Updated to linux-odroid-xu3:6.6.40, didn't come up aswell.

Switched to linux-armv7 and it's up and running. Feels a little laggier on the ssh term, but so far all seems to be working over here.

@graysky2 Sorry, been signed in into the wrong account, hardware is hc1. Can you please keep the other account out of this conversation?

**Comment by kyak** [comment]
It's a pity this got merged so quick even when users report that this kernel refuses to boot.

**Comment by kyak** [comment]
> @kyak - can you install the mainline linux package and see if that boots?
> 
> ```
> pacman -S linux-armv7
> ```

I've installed `linux-armv7` and it boots. Well, I mean that it doesn't crash right away like `linux-odroid-xu3`.

It drops me to emergency mode because it can't find `/dev/mmcblk0p1`, but it's not that important. It boots.

**Comment by polyzen** [comment]
> It's a pity this got merged so quick even when users report that this kernel refuses to boot.

This PR was open for months before it was merged. The reports came after.

Please help with https://github.com/hardkernel/linux/issues/437 as opposed to being snarky here.

**Pull request merged**
