### PR TITLE
Enable UEFI unified kernel image support to mkinitcpio.

### PR DESCRIPTION
**Pull request by sharpenedblade**
mkinitcpio hardcodes some paths to the x86_64 binaries, this patch also searches for the aarch64 ones. It will not effect armv7.

### CODE REVIEW

**Comment by mys721tx** [comment]
On VMWare Fusion 13, I tried to get around the default kernel image detection with `--kernelimage=/boot/Image` and the resultant kernel image is not bootable. There might be a bigger problem at hand for the unified kernel image.

**Comment by mys721tx** [comment]
On VMWare Fusion 13, I tried to get around the default kernel image detection with `--kernelimage=/boot/Image` and the resultant kernel image is not bootable. There might be a bigger problem at hand for the unified kernel image.

**Comment by sharpenedblade** [comment]
> On VMWare Fusion 13, I tried to get around the default kernel image detection with `--kernelimage=/boot/Image` and the resultant kernel image is not bootable. There might be a bigger problem at hand for the unified kernel image.

I read in the systemd repo that systemd-stub does not work on aarch64, even with good UEFI.

**Comment by mys721tx** [comment]
Inspired by systemd/systemd#23788, I made a uncompressed initramfs. Since it and `/boot/Image` are both uncompressed, it doesn't seem to be a problem with gzip. Considering UKI somehow works on Asahi (archlinux/mkinitcpio/#134), I am going to compare the kernel configs and report back.

**Comment by sharpenedblade** [comment]
[https://github.com/archlinux/mkinitcpio/pull/134](https://github.com/archlinux/mkinitcpio/pull/134) works for all aarch64 arch based distros, not just asahi. It works basically the same as this. Asahi is just alarm with a custom kernel and pre-bootloader stuff. It probably has to do with their kernel. Specifically, there kernel is binary is `vmzlinuz`, while ours is `Image`. `vmzlinuz` is probably the better thing to do (and most other distros do it too). I think a seperate issue to use a more standardized kernel should be opened first.

**Comment by jvdsn** [comment]
I replicated the setup in a QEMU VM (it's very tedious to reprovision the Oracle Cloud machines). When I try to load the EFI image from the EFI shell I get `Command Error Status: Load Error`.

This is what `bootctl` currently outputs (no `systemd-boot` installed yet):
```
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
System:
      Firmware: n/a (n/a)
 Firmware Arch: aa64
   Secure Boot: disabled (unsupported)
  TPM2 Support: no
  Boot into FW: supported

Current Boot Loader:
      Product: n/a
     Features: - Boot counting
               - Menu timeout control
               - One-shot menu timeout control
               - Default entry control
               - One-shot entry control
               - Support for XBOOTLDR partition
               - Support for passing random seed to OS
               - Load drop-in drivers
               - Support Type #1 sort-key field
               - Support @saved pseudo-entry
               - Support Type #1 devicetree field
               - Boot loader sets ESP information
          ESP: n/a
         File: `-n/a

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: no

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/4102b19b-4529-2641-ada7-9b4f79c70e8e)

Boot Loaders Listed in EFI Variables:
        Title: Arch Linux
           ID: 0x0008
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/4102b19b-4529-2641-ada7-9b4f79c70e8e
         File: `-/efi/EFI/Linux/archlinux-linux.efi

        Title: Arch Linux Fallback
           ID: 0x0009
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/4102b19b-4529-2641-ada7-9b4f79c70e8e
         File: `-/efi/EFI/Linux/archlinux-linux-fallback.efi

Boot Loader Entries:
        $BOOT: /efi (/dev/disk/by-partuuid/4102b19b-4529-2641-ada7-9b4f79c70e8e)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #2 (.efi)
        title: Arch Linux ARM (rolling) (archlinux-linux.efi)
           id: archlinux-linux.efi
       source: /efi/EFI/Linux/archlinux-linux.efi
     sort-key: archarm
      version: rolling
        linux: EFI/Linux/archlinux-linux.efi
      options: root=UUID=7663a807-9a29-4f4a-bc1b-eb1d4fc23fc1 rw console=tty1 c>
```

On my x86 VPS it looks like this:
```
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
System:
      Firmware: UEFI 2.70 (EDK II 1.00)
 Firmware Arch: x86_64
   Secure Boot: disabled (unsupported)
  TPM2 Support: no
  Boot into FW: supported

Current Boot Loader:
      Product: n/a
     Features: ✗ Boot counting
               ✗ Menu timeout control
               ✗ One-shot menu timeout control
               ✗ Default entry control
               ✗ One-shot entry control
               ✗ Support for XBOOTLDR partition
               ✗ Support for passing random seed to OS
               ✗ Load drop-in drivers
               ✗ Support Type #1 sort-key field
               ✗ Support @saved pseudo-entry
               ✗ Support Type #1 devicetree field
               ✓ Boot loader sets ESP information
         Stub: systemd-stub 252.3-1-arch
     Features: ✓ Stub sets ESP information
               ✓ Picks up credentials from boot partition
               ✓ Picks up system extension images from boot partition
               ✓ Measures kernel+command line+sysexts
          ESP: /dev/disk/by-partuuid/99978a17-fbcd-1d4c-a897-b8a41ec6e8a5
         File: └─EFI/Linux/archlinux-linux.efi

Random Seed:
 Passed to OS: no
 System Token: not set
       Exists: no

Available Boot Loaders on ESP:
          ESP: /efi (/dev/disk/by-partuuid/99978a17-fbcd-1d4c-a897-b8a41ec6e8a5)

Boot Loaders Listed in EFI Variables:
        Title: Arch Linux
           ID: 0x0002
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/99978a17-fbcd-1d4c-a897-b8a41ec6e8a5
         File: └─EFI/Linux/archlinux-linux.efi

        Title: Arch Linux Fallback
           ID: 0x0004
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/99978a17-fbcd-1d4c-a897-b8a41ec6e8a5
         File: └─EFI/Linux/archlinux-linux-fallback.efi

Boot Loader Entries:
        $BOOT: /efi (/dev/disk/by-partuuid/99978a17-fbcd-1d4c-a897-b8a41ec6e8a5)

Default Boot Loader Entry:
         type: Boot Loader Specification Type #2 (.efi)
        title: Arch Linux (rolling) (archlinux-linux.efi)
           id: archlinux-linux.efi
       source: /efi/EFI/Linux/archlinux-linux.efi
     sort-key: arch
      version: rolling
        linux: EFI/Linux/archlinux-linux.efi
      options: root=UUID=568800ea-f2e6-4f57-9de2-d99e936bee5d rw console=tty1 console=ttyS0
```

With `systemd-boot` installed, I get the following output in QEMU:
```
BdsDxe: loading Boot000A "Linux Boot Manager" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/\EFI\systemd\systemd-bootaa64.efi
BdsDxe: starting Boot000A "Linux Boot Manager" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/\EFI\systemd\systemd-bootaa64.efi
Error loading \EFI\Linux\archlinux-linux.efi: Load Error
BdsDxe: failed to start Boot000A "Linux Boot Manager" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/\EFI\systemd\systemd-bootaa64.efi: Load Error
BdsDxe: loading Boot0008 "Arch Linux" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/EFI\Linux\archlinux-linux.efi
BdsDxe: failed to load Boot0008 "Arch Linux" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/EFI\Linux\archlinux-linux.efi: Load Error
BdsDxe: loading Boot0009 "Arch Linux Fallback" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/EFI\Linux\archlinux-linux-fallback.efi
BdsDxe: starting Boot0009 "Arch Linux Fallback" from HD(1,GPT,4102B19B-4529-2641-ADA7-9B4F79C70E8E,0x800,0x82000)/EFI\Linux\archlinux-linux-fallback.efi
Overlapping PE sections detected. Boot may fail due to image memory corruption!


Synchronous Exception at 0x000000013B459670


Synchronous Exception at 0x000000013B459670
```

**Comment by sharpenedblade** [comment]
>`Overlapping PE sections detected. Boot may fail due to image memory corruption!`

This sounds like the magic constants used do not work for aarch64. Can you try building the image with 
```
$ stub_line=$(objdump -h "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" | tail -2 | head -1)
$ stub_size=0x$(echo "$stub_line" | awk '{print $3}')
$ stub_offs=0x$(echo "$stub_line" | awk '{print $4}')
$ osrel_offs=$((stub_size + stub_offs))
$ cmdline_offs=$((osrel_offs + $(stat -c%s "/usr/lib/os-release")))
$ splash_offs=$((cmdline_offs + $(stat -c%s "/etc/kernel/cmdline")))
$ linux_offs=$((splash_offs + $(stat -c%s "/usr/share/systemd/bootctl/splash-arch.bmp")))
$ initrd_offs=$((linux_offs + $(stat -c%s "vmlinuz-file")))
$ objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
    --add-section .cmdline="/etc/kernel/cmdline" \
    --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" \
    --change-section-vma .splash=$(printf 0x%x $splash_offs) \
    --add-section .linux="vmlinuz-file" \
    --change-section-vma .linux=$(printf 0x%x $linux_offs) \
    --add-section .initrd="initrd-file" \
    --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "linux.efi"
```
This will calculate the offsets, so it should work. (I got it from the arch wiki).

**Comment by mys721tx** [comment]
I managed to get it to work with the following!

```ShellSession
$ stub_line=$(objdump -h "/usr/lib/systemd/boot/efi/linuxaa64.efi.stub" | tail -2 | head -1)
$ stub_size=0x$(echo "$stub_line" | awk '{print $3}')
$ stub_offs=0x$(echo "$stub_line" | awk '{print $4}')
$ osrel_offs=$((stub_size + stub_offs))
$ cmdline_offs=$((osrel_offs + $(stat -c%s "/usr/lib/os-release")))
$ splash_offs=$((cmdline_offs + $(stat -c%s "/etc/kernel/cmdline")))
$ linux_offs=$((splash_offs + $(stat -c%s "/usr/share/systemd/bootctl/splash-arch.bmp")))
$ initrd_offs=$((linux_offs + $(stat -c%s "/boot/Image")))
$ objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
    --add-section .cmdline="/etc/kernel/cmdline" \
    --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" \
    --change-section-vma .splash=$(printf 0x%x $splash_offs) \
    --add-section .linux="/boot/Image" \
    --change-section-vma .linux=$(printf 0x%x $linux_offs) \
    --add-section .initrd="/boot/initramfs-linux.img" \
    --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
    "/usr/lib/systemd/boot/efi/linuxaa64.efi.stub" "/boot/EFI/Linux/archlinux-linux.efi"
```

**Comment by mys721tx** [comment]
And relevant offsets:

```
stub_line='  1 .data         00002000  0000000000014000  0000000000014000  00014000  2**2'
stub_size=0x00002000
stub_offs=0x0000000000014000
osrel_offs=90112
cmdline_offs=90451
splash_offs=90539
linux_offs=468765
initrd_offs=41539869
```

**Comment by mys721tx** [comment]
The following are the section headers of the EFI binaries generated by both methods. I did not see any obvious overrun yet `archlinux-linux-mkinitcpio.efi` is still not bootable.

```ShellSession
# objdump -h /efi/EFI/Linux/archlinux-linux-objcopy.efi

/efi/EFI/Linux/archlinux-linux-objcopy.efi:     file format pei-aarch64-little

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         00013000  0000000000001000  0000000000001000  00000400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .data         00002000  0000000000014000  0000000000014000  00013400  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 .osrel        00000153  0000000000016000  0000000000016000  00015400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .cmdline      00000058  0000000000016153  0000000000016153  00015600  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .splash       0005c572  00000000000161ab  00000000000161ab  00015800  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .linux        0272b200  000000000007271d  000000000007271d  00071e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .initrd       0078b3f4  000000000279d91d  000000000279d91d  0279d000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
# objdump -h /efi/EFI/Linux/archlinux-linux-mkinitcpio.efi.efi    

/efi/EFI/Linux/archlinux-linux-mkinitcpio.efi:     file format pei-aarch64-little

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         00013000  0000000000001000  0000000000001000  00000400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .data         00002000  0000000000014000  0000000000014000  00013400  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 .osrel        00000153  0000000000020000  0000000000020000  00015400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .cmdline      0000005a  0000000000030000  0000000000030000  00015600  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .splash       0005c572  0000000000040000  0000000000040000  00015800  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .linux        0272b200  0000000002000000  0000000002000000  00071e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .initrd       0078b3f4  0000000003000000  0000000003000000  0279d000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

**Comment by mys721tx** [comment]
Looks like the [VMA for initrd](https://github.com/archlinux/mkinitcpio/blob/33cfb0ac0ae29db671a267b8288aaa30761796ac/mkinitcpio#L369) is too low for the uncompressed Image (goes up to 0x472B200). mkinitcpio generated image works when I changed the VMA to 0x5000000. I'll work on a PR for the upstream to change the VMA to actual size.

**Comment by sharpenedblade** [comment]
> And relevant offsets:
> 
> ```
> stub_line='  1 .data         00002000  0000000000014000  0000000000014000  00014000  2**2'
> stub_size=0x00002000
> stub_offs=0x0000000000014000
> osrel_offs=90112
> cmdline_offs=90451
> splash_offs=90539
> linux_offs=468765
> initrd_offs=41539869
> ```

These offsets are very machine specific, adding auto detection to mkinitcpio would be very usefull, it shouldnt be a very big change. I can make a PR to auto detect offsets for everything

**Comment by mys721tx** [comment]
I made a [PR to upstream](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/182)! Hopefully this can solve the problem.

**Comment by sharpenedblade** [comment]
Fixed in upstream

**Pull request closed without merging**
