### PR TITLE
alarm/dkms-mt7610 - fixed post_install() path

### PR DESCRIPTION
**Pull request by phedoreanu**
Forgot to bump the version on the sources folder.

### CODE REVIEW

**Comment by ivkos** [comment]
@phedoreanu Can you please also edit the version in `dkms.conf`. It's currently `v3.0.0.2` but should match the package version, i.e. `v3.0.0.3`.

Thank you! :+1:

**Comment by phedoreanu** [comment]
Sorry, my bad. I also bumped the release. 

Cheers. :+1:

**Comment by kmihelich** [comment]
Checksums need to be updated.

**Comment by phedoreanu** [comment]
Updated and squashed.

**Pull request merged**
