### PR TITLE
alarm/firmware-imx to 8.24.r0.fbe0a4c

### PR DESCRIPTION
**Pull request by alexojegu**
Version used on Yocto Project 5.0 LTS (scarthgap): https://layers.openembedded.org/layerindex/recipe/402107/

### CODE REVIEW

**Comment by graysky2** [comment]
Are you using this package on the version in your PR on your hardware?  Any regressions?

**Comment by alexojegu** [comment]
I had done the installation manually, now I see that `sdma-imx6q.bin` is already provided by `linux-firmware`. With both I see the same error:
```
# dmesg | grep -i sdma
[    2.584580] imx-sdma 20ec000.dma-controller: Direct firmware load for imx/sdma/sdma-imx6q.bin failed with error -2
[    2.595021] imx-sdma 20ec000.dma-controller: external firmware not found, using ROM firmware
```

With `vpu` everything seems correct:
```
# dmesg | grep -i vpu 
[   23.290530] coda 2040000.vpu: Direct firmware load for vpu_fw_imx6q.bin failed with error -2
[   23.336027] coda 2040000.vpu: Using fallback firmware vpu/vpu_fw_imx6q.bin
[   23.353565] coda 2040000.vpu: Firmware code revision: 46076
[   23.363109] coda 2040000.vpu: Initialized CODA960.
[   23.372236] coda 2040000.vpu: Firmware version: 3.1.1
[   23.389606] coda 2040000.vpu: coda-jpeg-encoder registered as video6
[   23.403993] coda 2040000.vpu: coda-jpeg-decoder registered as video8
[   23.414005] coda 2040000.vpu: coda-video-encoder registered as video9
[   23.423058] coda 2040000.vpu: coda-video-decoder registered as video11
```

**Comment by alexojegu** [comment]
I'm not sure if it would be better to use `8.24.r0.fbe0a4c` as `pkgver` or if it could cause problems with future versions, where for example `pkgver` will just be `8.25`.

**Comment by alexojegu** [comment]
Changed version from `8.24_fbe0a4c` to `8.24.r0.fbe0a4c`.

**Comment by graysky2** [comment]
> I did the installation manually

To be clear, did you build and install from the `PKGBUILD` you are providing in this PR, NOT from a manual copy?  Also, per the rules, please squash all commits into a single.

**Comment by alexojegu** [comment]
Yes, I compiled and installed from the PKGBUILD that I am providing in this PR. And I think I have achieved squash all commits into a single.

**Pull request merged**
