### PR TITLE
core/linux-odroid-n2 to 4.9.213

### PR DESCRIPTION
**Pull request by jgmdev**
Same changes as previous pull #1770 request and now **config** file properly generated with **make menuconfig**

> Updated to 4.9.213 and enable console software cursor to fix missing cursor.
> 
> More details: https://forum.odroid.com/viewtopic.php?f=177&t=37431
> 
> The patch on https://forum.odroid.com/viewtopic.php?f=177&t=37431#p278056 for drivers/amlogic/media/osd/osd_fb.c isn't needed because it has been mainstreamed, only disabling CONFIG_AMLOGIC_MEDIA_FB_OSD2_CURSOR is needed now.

### CODE REVIEW

**Comment by kmihelich** [comment]
https://github.com/archlinuxarm/PKGBUILDs/blob/master/CONTRIBUTING.md

**Comment by jgmdev** [comment]
I think the only missing requirement was squashing the commits together which is properly done now. Sorry for missing this out.

**Comment by jgmdev** [comment]
ahh no I missed the proper md5sum for generated config :cry:

**Comment by jgmdev** [comment]
Now it really is properly done! Sorry for all the noise :(

**Pull request merged**
