### PR TITLE
[uboot-sunxi] add more boards and simplify u-boot pkgbuild

### PR DESCRIPTION
**Pull request by p5n**
But some packages will be renamed according to u-boot's defconfig names.

Added:
- Lamobo_R1
- Mele_M3
- Mele_M5
- Orangepi
- Orangepi_mini

package_*() functions and pkgname array are generated from boards list now.

There is no need to rebuild u-boot now, so I did not increase pkgrel.

### CODE REVIEW

**Comment by kmihelich** [comment]
Lemaker systems and derivatives will not be supported here.  Those will be removed before this PR is considered.

**Comment by p5n** [comment]
I removed

* Bananapi
* Bananapro

from the patch.

**Comment by p5n** [comment]
Also if the reason is the same as in https://github.com/archlinuxarm/PKGBUILDs/pull/892 I should say that this PR has no any uboot patches to "take on the responsibility to carry forward them".

You can generate boards array using something like
  grep 'CONFIG_ARCH_SUNXI' u-boot-2016.05/configs/*_defconfig
and build all boards that u-boot supports.

**Comment by p5n** [comment]
@kmihelich I updated this request against latest archlinuxarm/PKGBUILDs. It there any other reasons to don't merge it? Actually I don't know exactly which boards are "Copycat Chinese garbage"...

**Comment by kmihelich** [comment]
Unsupported platforms, and I have no interest in supporting them.

**Comment by p5n** [comment]
ok, but what about simplifying PKGBUILD? You may remove unsupported boards from _uboot_boards array.

**Comment by kmihelich** [comment]
Aside from the fact that it doesn't build, simplification is subjective in this instance and doesn't appear beneficial.  You're also renaming existing packages and breaking the upgrade path for them.

**Comment by p5n** [comment]
I was able to build it from p5n/PKGBUILDs

$ ls -1 *.xz
uboot-a10-olinuxino-lime-2017.01-2-armv7h.pkg.tar.xz
uboot-a10s-olinuxino-m-2017.01-2-armv7h.pkg.tar.xz
uboot-a13-olinuxino-2017.01-2-armv7h.pkg.tar.xz
uboot-a13-olinuxinom-2017.01-2-armv7h.pkg.tar.xz
uboot-a20-olinuxino-lime-2017.01-2-armv7h.pkg.tar.xz
uboot-a20-olinuxino-lime2-2017.01-2-armv7h.pkg.tar.xz
uboot-a20-olinuxino-micro-2017.01-2-armv7h.pkg.tar.xz
uboot-cubieboard-2017.01-2-armv7h.pkg.tar.xz
uboot-cubieboard2-2017.01-2-armv7h.pkg.tar.xz
uboot-cubieboard4-2017.01-2-armv7h.pkg.tar.xz
uboot-cubietruck-2017.01-2-armv7h.pkg.tar.xz
uboot-cubietruck-plus-2017.01-2-armv7h.pkg.tar.xz
uboot-lamobo-r1-2017.01-2-armv7h.pkg.tar.xz
uboot-linksprite-pcduino-2017.01-2-armv7h.pkg.tar.xz
uboot-linksprite-pcduino3-2017.01-2-armv7h.pkg.tar.xz
uboot-linksprite-pcduino3-nano-2017.01-2-armv7h.pkg.tar.xz
uboot-mele-m3-2017.01-2-armv7h.pkg.tar.xz
uboot-mele-m5-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-2-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-lite-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-mini-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-one-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-pc-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-pc-plus-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-plus-2017.01-2-armv7h.pkg.tar.xz
uboot-orangepi-plus2e-2017.01-2-armv7h.pkg.tar.xz

regarding update path, I'll make separate pull request

**Pull request closed without merging**
