### PR TITLE
alarm/kodi-rbp-git to 16.0b2.20151121-1

### PR DESCRIPTION
**Pull request by phedoreanu**
```
configure: WARNING: unrecognized options: --disable-goom, --disable-xrandr, \
--disable-projectm, --enable-rsxs
```

### CODE REVIEW

**Comment by moonman** [comment]
Why --disable-optical-drive ?

**Comment by phedoreanu** [comment]
How do you even link a DVD-ROM to a Raspberry Pi?

**Comment by moonman** [comment]
There are plenty of external bluray and dvd drives available with USB as an
interface?

**Comment by phedoreanu** [comment]
Ok, I reverted that flag.

**Comment by moonman** [comment]
Thanks

**Pull request merged**
