### PR TITLE
use btattach instead of the deprecated hciattach

### PR DESCRIPTION
**Pull request by alexojegu**
The tool hciattach was removed from bluez-utils and replaced by btattach, [according to documentation](https://wiki.archlinux.org/title/Bluetooth#Deprecated_BlueZ_tools).

### CODE REVIEW

**Comment by graysky2** [comment]
@xeladejo - Plz update checksums

**Comment by xeladejo** [comment]
@graysky2 - Ups, I forgot excuse me

**Comment by xeladejo** [comment]
Seems `brcm_patchram_plus` is [deprecated](https://github.com/LibreELEC/brcmfmac_sdio-firmware/blob/master/README.md):

> Use of hciattach and brcm_patchram_plus are discouraged as firmware loading can be triggered by including `compatible = "brcm,bcm43438-bt";` nodes in device-tree.

I don't know if this device-tree requirement is included in Arch Linux ARM.

**Comment by xeladejo** [comment]
Alright, for the above to work would be necessary patch the device tree for `wandboard-revc1`. I am not sure if this may have other implications and if the Arch Linux ARM team are willing to make this change on `linux-armv7` package.

Here is the patch from LibreELEC: https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/NXP/devices/iMX6/patches/linux/linux-001-imx6qdl-wandboard-revc1-dtsi-bluetooth.patch

**Comment by alexojegu** [comment]
Alright @graysky2, forget all about patching the device tree. But can you just merge this pull request to replace `hciattach` with `btattach` in `brcm43xx.service`?

**Comment by graysky2** [comment]
Yes, please see https://github.com/archlinuxarm/PKGBUILDs/commit/e1c58d239b7f9c5a76855afa62a2eb1e13989575

**Comment by graysky2** [comment]
@alexojegu - Yes, please see https://github.com/archlinuxarm/PKGBUILDs/commit/e1c58d239b7f9c5a76855afa62a2eb1e13989575 and https://github.com/archlinuxarm/PKGBUILDs/commit/2a01b6832854be9d70f6f473bcda101bd01c5b93

Can you please verify that 1.1-5 behaves as it should?  I needed to modify the build command to get it from erroring out.

**Comment by alexojegu** [comment]
I can see the new version at https://archlinuxarm.org/packages/armv7h/firmware-brcm43xx but when trying to download using the page link I get 404.

And it doesn't seem to have synchronized in the mirrors:
```
# pacman -Q firmware-brcm43xx
firmware-brcm43xx 1.1-3
# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
warning: uboot-wandboard: local (2024.04-1) is newer than alarm (2018.03-1) there is nothing to do
```

**Comment by graysky2** [comment]
Kevin must be rebuilding some stuff and has temporary disabled syncing.  Please report back when the push occurs.

Unrelated: are you using the linux-armv7h kernel?  If so, do you mind testing the [6.9.3 update](https://archlinuxarm.org/forum/viewtopic.php?f=60&t=16928) I built several weeks ago.  I do not have hardware for testing and I do not want to push if there is breakage.  Please do not test if you are unsure how to recover should the kernel package render your system unbootable.

**Comment by graysky2** [comment]
Thanks for testing and for reporting back

**Comment by alexojegu** [comment]
About `firmware-brcm43xx`, there seems to be a problem with `brcm_patchram_plus`:
```
x brcm43xx-firmware.service - Broadcom 43xx firmware update
     Loaded: loaded (/usr/lib/systemd/system/brcm43xx-firmware.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2024-06-27 10:35:07 UTC; 44s ago
 Invocation: 1e36902bb84d429f86fcc9b38a460414
    Process: 446 ExecStart=/usr/lib/systemd/scripts/brcm43xx-firmware-update (code=exited, status=1/FAILURE)
   Main PID: 446 (code=exited, status=1/FAILURE)

Jun 27 10:35:07 alarm systemd[1]: Starting Broadcom 43xx firmware update...
Jun 27 10:35:07 alarm brcm43xx-firmware-update[446]: Warning: Using self generated MAC address! MAC_ADDR should be defined in /etc/conf.d/bcm43xx.
Jun 27 10:35:07 alarm brcm43xx-firmware-update[446]: Updating bluetooth firmware via /dev/ttymxc2 from /lib/firmware/brcm/bcm4330.hcd.
Jun 27 10:35:07 alarm brcm43xx-firmware-update[451]: /usr/lib/systemd/scripts/brcm43xx-firmware-update: line 63: /usr/bin/brcm_patchram_plus: cannot execute binary file: Exec format error
Jun 27 10:35:07 alarm systemd[1]: brcm43xx-firmware.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 10:35:07 alarm systemd[1]: brcm43xx-firmware.service: Failed with result 'exit-code'.
Jun 27 10:35:07 alarm systemd[1]: Failed to start Broadcom 43xx firmware update.
```

**Comment by graysky2** [comment]
I was afraid of that... the upstream code required building with a switch to mask build errors: https://github.com/archlinuxarm/PKGBUILDs/commit/2a01b6832854be9d70f6f473bcda101bd01c5b93

If that is rendering the executable bad, upstream needs to fix something or we need to build with some other switch.

**Comment by alexojegu** [comment]
The code hasn't been changed since 2011 and worked before... so I think it's better to build it with errors than nothing (I'm sure Broadcom won't fix it today).

Unrelated: If you lack the necessary hardware to test ARMv7 Kernel, so a question arises, is Arch Linux ARM considering stopping ARMv7 support in the near future?

**Comment by graysky2** [comment]
Building with the errors means the build does not complete/executable is created.  I suspect the errors are related to gcc-14 vs gcc-12.

I am not the only ArchARM maintainer, others have hardware.  The strategic direction of the Distro is also not set by me.

**Pull request closed without merging**
